import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { loadAtlasGraph } from '@agent-atlas/core';
import { generateMarkdownViews, renderEntityCard, renderPackageReadmes, renderRepositoryReadme } from './index.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const examplesRoot = path.resolve(__dirname, '../../../examples');

describe('generateMarkdownViews', () => {
  it('generates compact public markdown views', async () => {
    const graph = await loadAtlasGraph(path.join(examplesRoot, 'personal-ops-sanitized'));
    const files = generateMarkdownViews(graph, { profile: 'public' });
    const filePaths = files.map((file) => file.path);

    expect(filePaths).toContain('atlas.md');
    expect(filePaths).toContain('verification.md');
    expect(filePaths).toContain('components/index.md');
    expect(filePaths).toContain('domains/calendar.md');
    expect(filePaths).toContain('domains/index.md');
    expect(filePaths).toContain('workflows/plan-week.md');
    expect(filePaths).toContain('workflows/index.md');
    expect(filePaths).toContain('components/weekly-planner.md');
    expect(filePaths).not.toContain('documents/weekly-planning-system.md');
    const root = files.find((file) => file.path === 'atlas.md')?.content ?? '';
    expect(root).toContain('<!-- Generated by Agent Atlas. Do not edit directly. -->');
    expect(root).toContain('# Atlas overview');
    expect(root).toContain('## Start here');
    const domainIndex = files.find((file) => file.path === 'domains/index.md')?.content ?? '';
    expect(domainIndex).toContain('# Domain Index');
    expect(domainIndex).toContain('[Calendar](calendar.md)');
  });

  it('includes private-profile files when requested', async () => {
    const graph = await loadAtlasGraph(path.join(examplesRoot, 'personal-ops-sanitized'), {
      profile: 'private',
    });
    const files = generateMarkdownViews(graph, { profile: 'private' });

    expect(files.map((file) => file.path)).toContain('documents/weekly-planning-system.md');
    expect(files.find((file) => file.path === 'documents/weekly-planning-system.md')?.content).toContain(
      'notion://page/sanitized-weekly-planning',
    );
  });

  it('deduplicates matching CLI command labels in interface indexes', () => {
    const files = generateMarkdownViews(
      {
        rootPath: '.',
        index: {
          entitiesById: new Map(),
          outgoingById: new Map(),
          incomingById: new Map(),
        },
        diagnostics: [],
        entities: [
          {
            id: 'interface:root.browser-status',
            kind: 'interface',
            title: 'pnpm orch browser:probe:status',
            summary: 'Check browser status from the root CLI.',
            visibility: 'public',
            metadata: {
              cli: {
                cli_name: 'pnpm orch',
                command: 'browser:probe:status',
                group: 'Browser Commands',
              },
            },
          },
          {
            id: 'interface:package.browser-status',
            kind: 'interface',
            title: 'pnpm orch browser:probe:status',
            summary: 'Check browser status from the package CLI contribution.',
            visibility: 'public',
            metadata: {
              cli: {
                cli_name: 'pnpm orch',
                command: 'browser:probe:status',
                group: 'Browser Commands',
              },
            },
          },
        ],
        edges: [],
      },
      { profile: 'public' },
    );

    const index = files.find((file) => file.path === 'interfaces/index.md')?.content ?? '';

    expect(index.match(/pnpm orch browser:probe:status/g)).toHaveLength(1);
  });

  it('redacts private references from public markdown cards', () => {
    const markdown = renderEntityCard(
      {
        id: 'document:release-process',
        kind: 'document',
        title: 'Release Process',
        summary: 'Internal release process.',
        visibility: 'public',
        uri: 'notion://page/sanitized-release-process',
      },
      [],
      'public',
    );

    expect(markdown).toContain('[redacted: private reference]');
    expect(markdown).not.toContain('notion://page/sanitized-release-process');
  });

  it('renders package component cards as package entrypoints', () => {
    const markdown = renderEntityCard(
      {
        id: 'component:package.example-core',
        kind: 'component',
        title: '@example/core',
        summary: 'Core package.',
        visibility: 'public',
        metadata: {
          package: {
            root: 'packages/core',
            path: 'packages/core/package.json',
            scripts: ['build'],
            exports: ['.', './cli'],
          },
        },
      },
      [
        {
          source: 'component:package.example-core',
          target: 'interface:package-script.example-core.build',
          type: 'contains',
          provenance: 'generated',
        },
        {
          source: 'component:package.example-core',
          target: 'test-scope:generated.package.example-core',
          type: 'contains',
          provenance: 'generated',
        },
      ],
      'public',
    );

    expect(markdown).toContain('## Drill Down');
    expect(markdown).toContain('### Package Facts');
    expect(markdown).toContain('- root: `packages/core`');
    expect(markdown).toContain('### Interfaces');
    expect(markdown).toContain('`interface:package-script.example-core.build`');
    expect(markdown).toContain('### Tests');
  });

  it('renders a compact repository README from visible atlas entities', () => {
    const markdown = renderRepositoryReadme(
      {
        rootPath: '.',
        index: {
          entitiesById: new Map(),
          outgoingById: new Map(),
          incomingById: new Map(),
        },
        diagnostics: [],
        entities: [
          {
            id: 'repository:example',
            kind: 'repository',
            title: 'example',
            summary: 'Example repository.',
            visibility: 'public',
            commands: [{ command: 'pnpm test', purpose: 'Run tests.' }],
            metadata: {
              readme: {
                start_here: ['Run `pnpm start`.', 'Read `AGENTS.md`.'],
                current_truth_order: ['Live refresh.', 'Generated current state.'],
                key_docs: [{ label: 'Agent Rules', path: 'AGENTS.md', note: 'Agent guidance.' }],
                durable_state: [{ path: 'registry/', note: 'Registry data.' }],
                operational_notes: ['Long-running launches need long timeouts.'],
                cli: {
                  overview: ['Use `example` for repository automation.'],
                  reference: {
                    label: 'CLI Reference',
                    path: 'docs/generated/cli-command-reference.md',
                    note: 'Generated command details.',
                  },
                },
                sections: [{ title: 'Custom Section', items: ['Custom item.'] }],
              },
            },
            relations: [
              { type: 'contains', target: 'workflow:ship' },
              { type: 'contains', target: 'document:docs-index' },
            ],
          },
          {
            id: 'workflow:ship',
            kind: 'workflow',
            title: 'Ship',
            summary: 'Release the package.',
            visibility: 'public',
          },
          {
            id: 'domain:example-domain',
            kind: 'domain',
            title: 'Example Domain',
            summary: 'Top-level domain context.',
            visibility: 'public',
          },
          {
            id: 'document:docs-index',
            kind: 'document',
            title: 'Docs Index',
            summary: 'Documentation entrypoint.',
            visibility: 'public',
            uri: 'docs/index.md',
          },
          {
            id: 'test-scope:repo-tests',
            kind: 'test-scope',
            title: 'Repo Tests',
            summary: 'Repository verification commands.',
            visibility: 'public',
            commands: [{ command: 'pnpm test', purpose: 'Run the repository tests.' }],
          },
          {
            id: 'capability:agent-skill.ship',
            kind: 'capability',
            title: 'Ship skill',
            summary: 'Use when releasing the package.',
            visibility: 'public',
            uri: '.agents/skills/ship/SKILL.md',
          },
          {
            id: 'component:package.example-core',
            kind: 'component',
            title: '@example/core',
            summary: 'Core package.',
            visibility: 'public',
            uri: 'packages/core/package.json',
            metadata: {
              package: {
                name: '@example/core',
                root: 'packages/core',
                path: 'packages/core/package.json',
                scripts: ['build', 'test'],
                exports: ['.', './cli'],
              },
            },
          },
          {
            id: 'document:generated.agents-skills-ship-skill',
            kind: 'document',
            title: 'Ship skill',
            summary: 'Markdown document at .agents/skills/ship/SKILL.md.',
            visibility: 'public',
            uri: '.agents/skills/ship/SKILL.md',
          },
          {
            id: 'interface:example-cli.validate',
            kind: 'interface',
            title: 'example validate',
            summary: 'Validate repository metadata.',
            visibility: 'public',
            metadata: {
              cli: {
                cli_name: 'example',
                command: 'validate',
                usage: 'example validate [--json]',
                group: 'Validation Commands',
                group_description: 'Commands for validating repository metadata and generated artifacts.',
                importance: 'common',
                lifecycle: ['verify'],
                tasks: ['validate repository metadata'],
              },
            },
          },
          {
            id: 'document:private-runbook',
            kind: 'document',
            title: 'Private Runbook',
            summary: 'Private operational runbook.',
            visibility: 'private',
            uri: 'notion://page/private',
          },
        ],
        edges: [
          { source: 'repository:example', target: 'domain:example-domain', type: 'contains', provenance: 'explicit' },
          { source: 'repository:example', target: 'workflow:ship', type: 'contains', provenance: 'explicit' },
          { source: 'repository:example', target: 'capability:agent-skill.ship', type: 'contains', provenance: 'explicit' },
          { source: 'repository:example', target: 'document:docs-index', type: 'contains', provenance: 'explicit' },
          { source: 'repository:example', target: 'component:package.example-core', type: 'contains', provenance: 'generated' },
        ],
      },
      { profile: 'public' },
    );

    expect(markdown).toContain('<!-- Generated by Agent Atlas. Do not edit directly. -->');
    expect(markdown).toContain('# example');
    expect(markdown).toContain('- Run `pnpm start`.');
    expect(markdown).toContain('## Current Truth Order');
    expect(markdown).toContain('- [Agent Rules](AGENTS.md) - Agent guidance.');
    expect(markdown).toContain('- `registry/` - Registry data.');
    expect(markdown).toContain('## Operational Notes');
    expect(markdown).toContain('## Common Entry Points');
    expect(markdown).toContain('| Validate repository metadata. | `example validate` |');
    expect(markdown).toContain('## CLI');
    expect(markdown).toContain('- Use `example` for repository automation.');
    expect(markdown).toContain(
      '- Full command reference: [CLI Reference](docs/generated/cli-command-reference.md) - Generated command details.',
    );
    expect(markdown).toContain('### Command Groups');
    expect(markdown).toContain('| Group | Purpose | Example |');
    expect(markdown).toContain(
      '| [Validation Commands](docs/generated/cli-command-reference.md#validation-commands) (1) | Commands for validating repository metadata and generated artifacts. | `example validate` |',
    );
    expect(markdown).toContain('## Custom Section');
    expect(markdown).toContain('## Domains');
    expect(markdown).toContain('`domain:example-domain` - Example Domain: Top-level domain context.');
    expect(markdown).not.toContain('## Agent Capabilities');
    expect(markdown).not.toContain('## Packages');
    expect(markdown).not.toContain('document:generated.agents-skills-ship-skill');
    expect(markdown).toContain('## Drill Down');
    expect(markdown).toContain('- Source-derived inventory: `docs/generated/source-derived-reference.md`.');
    expect(markdown).toContain('Documentation map: [Docs Index](docs/index.md).');
    expect(markdown).toContain('- Release the package.');
    expect(markdown).toContain('## Verification');
    expect(markdown).toContain('`pnpm test` - Run tests.');
    expect(markdown).toContain('- Scoped verification map: `docs/agents/verification.md`.');
    expect(markdown).not.toContain('## Source-Derived Surfaces');
    expect(markdown).not.toContain('Private Runbook');
    expect(markdown).not.toContain('notion://page/private');
  });

  it('renders package README entrypoints for workspace packages', () => {
    const files = renderPackageReadmes(
      {
        rootPath: '.',
        index: {
          entitiesById: new Map(),
          outgoingById: new Map(),
          incomingById: new Map(),
        },
        diagnostics: [],
        entities: [
          {
            id: 'component:package.example-core',
            kind: 'component',
            title: '@example/core',
            summary: 'Core package for graph loading.',
            visibility: 'public',
            uri: 'packages/core/package.json',
            code: { paths: ['packages/core/**'], entrypoints: ['packages/core/package.json'] },
            commands: [
              { command: 'pnpm --dir packages/core build', purpose: 'Build the package.' },
              { command: 'pnpm --dir packages/core test', purpose: 'Run package tests.' },
            ],
            metadata: {
              package: {
                name: '@example/core',
                root: 'packages/core',
                path: 'packages/core/package.json',
                scripts: ['build', 'test'],
                exports: ['.', './cli'],
              },
            },
          },
          {
            id: 'interface:package-script.example-core.test',
            kind: 'interface',
            title: '@example/core test',
            summary: 'Run package tests.',
            visibility: 'public',
          },
          {
            id: 'interface:example-core-cli.inspect',
            kind: 'interface',
            title: 'example core inspect',
            summary: 'Inspect core package state.',
            visibility: 'public',
            metadata: {
              cli: {
                cli_name: 'example',
                command: 'core:inspect',
                usage: 'example core:inspect --json',
              },
            },
          },
          {
            id: 'test-scope:generated.package.example-core',
            kind: 'test-scope',
            title: '@example/core tests',
            summary: 'Generated package test scope.',
            visibility: 'public',
          },
        ],
        edges: [
          { source: 'interface:package-script.example-core.test', target: 'component:package.example-core', type: 'part-of', provenance: 'generated' },
          { source: 'interface:example-core-cli.inspect', target: 'component:package.example-core', type: 'part-of', provenance: 'generated' },
          { source: 'test-scope:generated.package.example-core', target: 'component:package.example-core', type: 'part-of', provenance: 'generated' },
        ],
      },
      { profile: 'public' },
    );

    expect(files).toHaveLength(1);
    expect(files[0]?.path).toBe('packages/core/README.md');
    expect(files[0]?.content).toContain('# @example/core');
    expect(files[0]?.content).toContain('- Package root: `packages/core`.');
    expect(files[0]?.content).toContain('## Code');
    expect(files[0]?.content).toContain('- `pnpm --dir packages/core test` - Run package tests.');
    expect(files[0]?.content).toContain('## Interfaces');
    expect(files[0]?.content).toContain(
      '- `example core:inspect --json` - Inspect core package state. (`interface:example-core-cli.inspect`)',
    );
    expect(files[0]?.content).toContain('- `interface:package-script.example-core.test` - Run package tests.');
    expect(files[0]?.content).toContain('## Verification');
  });

  it('infers useful README orientation without repository readme prose', () => {
    const markdown = renderRepositoryReadme(
      {
        rootPath: '.',
        index: {
          entitiesById: new Map(),
          outgoingById: new Map(),
          incomingById: new Map(),
        },
        diagnostics: [],
        entities: [
          {
            id: 'repository:example',
            kind: 'repository',
            title: 'example',
            summary: 'Example control plane for routing work.',
            visibility: 'public',
            commands: [
              { command: 'pnpm session:start', purpose: 'Start a normal repo session.' },
              { command: 'pnpm verify:session', purpose: 'Run closeout verification.' },
            ],
          },
          {
            id: 'workflow:packet-routing',
            kind: 'workflow',
            title: 'Packet Routing',
            summary: 'Turns current evidence into bounded work packets.',
            visibility: 'public',
          },
          {
            id: 'component:orchestrator-cli',
            kind: 'component',
            title: 'Orchestrator CLI',
            summary: 'Provides command-line workflows.',
            visibility: 'public',
            code: { paths: ['packages/orchestrator-cli/src/**'] },
          },
          {
            id: 'document:agents',
            kind: 'document',
            title: 'AGENTS.md',
            summary: 'Agent guidance.',
            visibility: 'public',
            uri: 'AGENTS.md',
          },
          {
            id: 'document:docs-index',
            kind: 'document',
            title: 'Docs Index',
            summary: 'Documentation map.',
            visibility: 'public',
            uri: 'docs/index.md',
          },
          {
            id: 'interface:example-cli.packet-create',
            kind: 'interface',
            title: 'example packet:create',
            summary: 'Create packets.',
            visibility: 'public',
            metadata: {
              cli: {
                cli_name: 'example',
                command: 'packet:create',
                group: 'Packet Commands',
                group_description: 'Commands for creating and routing work packets.',
              },
            },
          },
          {
            id: 'test-scope:session-verification',
            kind: 'test-scope',
            title: 'Session Verification',
            summary: 'Closeout verification.',
            visibility: 'public',
            commands: [{ command: 'pnpm verify:session', purpose: 'Run closeout verification.' }],
          },
        ],
        edges: [
          { source: 'repository:example', target: 'workflow:packet-routing', type: 'contains', provenance: 'explicit' },
          { source: 'repository:example', target: 'component:orchestrator-cli', type: 'contains', provenance: 'explicit' },
          { source: 'repository:example', target: 'document:agents', type: 'documented-in', provenance: 'explicit' },
          { source: 'repository:example', target: 'document:docs-index', type: 'documented-in', provenance: 'explicit' },
        ],
      },
      { profile: 'public' },
    );

    expect(markdown).toContain('example is an example control plane for routing work.');
    expect(markdown).toContain('- Most repo workflows are exposed through the CLI overview below.');
    expect(markdown).toContain('- Use [Docs Index](docs/index.md) as the documentation map for deeper architecture and operating-model context.');
    expect(markdown).toContain('## What This Repo Does');
    expect(markdown).toContain('- Turns current evidence into bounded work packets.');
    expect(markdown).toContain('## Normal Use');
    expect(markdown).toContain('- Start with `pnpm session:start` to start a normal repo session.');
    expect(markdown).toContain('- Use `example <command>` for the repo-supported workflows listed in the command groups below.');
    expect(markdown).toContain('## Key Docs');
    expect(markdown).toContain('- [AGENTS.md](AGENTS.md) - Repo-local operating instructions and agent guidance.');
    expect(markdown).toContain('- [Docs Index](docs/index.md) - Documentation map and deeper docs entrypoint.');
    expect(markdown).toContain('## Where Things Live');
    expect(markdown).toContain('- `packages/` - Workspace packages and implementation surfaces.');
    expect(markdown).toContain('## Common Entry Points');
    expect(markdown).toContain('| Create packets. | `example packet:create` |');
    expect(markdown).toContain('| Packet Commands (1) | Commands for creating and routing work packets. | `example packet:create` |');
    expect(markdown).toContain('- `pnpm verify:session` - Run closeout verification.');
  });
});
