import type { AtlasEntity, AtlasEntityId, AtlasEntityKind } from '@agent-atlas/schema';
import {
  createAtlasOverview,
  createGraphIndex,
  renderAtlasOverviewMarkdown,
  type AtlasGraph,
  type AtlasGraphEdge,
} from '@agent-atlas/core';
import type { AtlasProfile } from '@agent-atlas/core';

export type MarkdownProfile = AtlasProfile;

export interface MarkdownGenerationOptions {
  profile?: MarkdownProfile;
}

export interface GeneratedMarkdownFile {
  path: string;
  content: string;
}

interface ReadmeLinkItem {
  label: string;
  path: string;
  note?: string;
}

interface ReadmePathItem {
  path: string;
  note?: string;
}

interface ReadmeSection {
  title: string;
  items: string[];
}

interface ReadmeCliMetadata {
  overview?: string[];
  reference?: ReadmeLinkItem;
}

interface CliInterfaceGroup {
  title: string;
  description?: string;
  commands: string[];
  items: CliInterfaceItem[];
}

interface CliInterfaceItem {
  label: string;
  command: string;
  summary: string;
  importance?: string;
  lifecycle: string[];
  audience: string[];
  tasks: string[];
}

interface RepositoryReadmeMetadata {
  start_here?: string[];
  overview?: string[];
  current_truth_order?: string[];
  key_docs?: ReadmeLinkItem[];
  durable_state?: ReadmePathItem[];
  operational_notes?: string[];
  sections?: ReadmeSection[];
  cli?: ReadmeCliMetadata;
}

const GENERATED_HEADER = '<!-- Generated by Agent Atlas. Do not edit directly. -->';
const README_CLI_GROUP_COMMAND_LIMIT = 1;

const CARD_KIND_DIRECTORIES: Partial<Record<AtlasEntityKind, string>> = {
  domain: 'domains',
  workflow: 'workflows',
  component: 'components',
  capability: 'capabilities',
  interface: 'interfaces',
  resource: 'resources',
  document: 'documents',
};

export function generateMarkdownViews(
  graph: AtlasGraph,
  options: MarkdownGenerationOptions = {},
): GeneratedMarkdownFile[] {
  const profile = options.profile ?? 'public';
  const entities = filterEntitiesByProfile(graph.entities, profile);
  const entityIds = new Set(entities.map((entity) => entity.id));
  const edges = graph.edges.filter((edge) => entityIds.has(edge.source) && entityIds.has(edge.target));
  const files: GeneratedMarkdownFile[] = [
    {
      path: 'atlas.md',
      content: renderRootAtlasView(entities, edges, profile),
    },
    {
      path: 'verification.md',
      content: renderVerificationView(entities, edges, profile),
    },
  ];

  for (const entity of entities) {
    const directory = CARD_KIND_DIRECTORIES[entity.kind];
    if (!directory) {
      continue;
    }

    files.push({
      path: `${directory}/${entitySlug(entity.id)}.md`,
      content: renderEntityCard(entity, edges, profile),
    });
  }

  for (const [kind, directory] of Object.entries(CARD_KIND_DIRECTORIES) as Array<[AtlasEntityKind, string]>) {
    const directoryEntities = entities.filter((entity) => entity.kind === kind);
    if (directoryEntities.length === 0) {
      continue;
    }
    files.push({
      path: `${directory}/index.md`,
      content: renderEntityDirectoryIndex(kind, directoryEntities, profile),
    });
  }

  return files.sort((left, right) => left.path.localeCompare(right.path));
}

export function renderRepositoryReadme(
  graph: AtlasGraph,
  options: MarkdownGenerationOptions = {},
): string {
  const profile = options.profile ?? 'public';
  const entities = filterEntitiesByProfile(graph.entities, profile);
  const entityIds = new Set(entities.map((entity) => entity.id));
  const edges = graph.edges.filter((edge) => entityIds.has(edge.source) && entityIds.has(edge.target));
  const repository = entities.find((entity) => entity.kind === 'repository');
  const title = repository?.title ?? 'Repository';
  const summary = repository?.summary ?? 'Atlas-generated repository orientation.';
  const domains = collectReadmeEntities(undefined, 'domain', entities, edges).slice(0, 6);
  const workflows = collectReadmeEntities(repository?.id, 'workflow', entities, edges).slice(0, 8);
  const components = collectReadmeEntities(repository?.id, 'component', entities, edges)
    .filter((entity) => !isPackageComponent(entity))
    .slice(0, 10);
  const allDocuments = collectReadmeEntities(repository?.id, 'document', entities, edges)
    .filter((entity) => !isAgentSkillDocument(entity));
  const globalDocuments = entities
    .filter((entity) => entity.kind === 'document')
    .filter((entity) => !isAgentSkillDocument(entity));
  const documents = allDocuments.slice(0, 8);
  const tests = collectReadmeEntities(repository?.id, 'test-scope', entities, edges).slice(0, 8);
  const commands = collectReadmeCommands(repository, tests);
  const cliInterfaces = collectReadmeCliInterfaces(repository?.id, entities, edges);
  const readmeMetadata = readRepositoryReadmeMetadata(repository);
  const docsIndex = allDocuments.find((document) => document.uri === 'docs/index.md');
  const cliReference = readmeMetadata.cli?.reference ?? findCliReference(allDocuments) ?? findCliReference(globalDocuments);
  const cliGroups = groupCliInterfaces(cliInterfaces);
  const defaultKeyDocs = collectDefaultKeyDocs([...allDocuments, ...globalDocuments], cliReference);
  const defaultDurableState = collectDefaultDurableState(entities);
  const sessionStart = findSessionStartCommand(commands, cliGroups);
  const sourceNotes = [
    ...(repository?.agent?.risk_notes ?? []),
    'This README is generated from Agent Atlas metadata. Update `.agent-atlas/**` or the referenced canonical docs, then regenerate it.',
  ];
  const lines = [
    GENERATED_HEADER,
    '',
    `# ${title}`,
    '',
    humanRepositorySummary(repository),
    '',
    '## Quick Orientation',
    '',
    ...renderReadmeList(
      readmeMetadata.overview ??
        readmeMetadata.start_here ??
        buildDefaultQuickOrientation(docsIndex, cliGroups, cliReference),
    ),
  ];

  appendGeneratedOverviewSection(lines, readmeMetadata, repository, workflows, components, cliGroups);
  appendNormalUseSection(lines, readmeMetadata, sessionStart, cliGroups, tests, commands);
  appendCommonEntryPointsSection(lines, cliGroups);
  appendConfiguredSections(lines, readmeMetadata.sections);
  appendReadmeTextSection(lines, 'Current Truth Order', readmeMetadata.current_truth_order);
  appendCliSection(lines, readmeMetadata.cli, cliReference, cliGroups);
  appendReadmePathSection(lines, 'Where Things Live', readmeMetadata.durable_state ?? defaultDurableState);
  appendReadmeLinkSection(lines, 'Key Docs', readmeMetadata.key_docs ?? defaultKeyDocs);
  appendReadmeSection(lines, 'Domains', domains);
  appendReadmeSection(lines, 'Key Implementation Surfaces', components);
  appendDrillDownSection(lines, documents);
  appendVerificationSection(lines, tests, commands);
  appendReadmeTextSection(lines, 'Operational Notes', readmeMetadata.operational_notes);

  if (commands.length > 0 && cliGroups.length === 0) {
    lines.push('', '## Commands', '');
    for (const command of commands) {
      lines.push(`- \`${command.command}\`${command.purpose ? ` - ${command.purpose}` : ''}`);
    }
  }

  lines.push('', '## Generated Source', '', ...sourceNotes.map((note) => `- ${note}`));
  return `${lines.join('\n')}\n`;
}

export function renderPackageReadmes(
  graph: AtlasGraph,
  options: MarkdownGenerationOptions = {},
): GeneratedMarkdownFile[] {
  const profile = options.profile ?? 'public';
  const entities = filterEntitiesByProfile(graph.entities, profile);
  const entityIds = new Set(entities.map((entity) => entity.id));
  const edges = graph.edges.filter((edge) => entityIds.has(edge.source) && entityIds.has(edge.target));
  return entities
    .filter(isPackageComponent)
    .map((entity) => {
      const metadata = readPackageMetadata(entity);
      return metadata.root && metadata.root !== '.'
        ? {
            path: `${metadata.root}/README.md`,
            content: renderPackageReadme(entity, entities, edges, profile),
          }
        : undefined;
    })
    .filter((file): file is GeneratedMarkdownFile => file !== undefined)
    .sort((left, right) => left.path.localeCompare(right.path));
}

export function renderEntityCard(
  entity: AtlasEntity,
  edges: AtlasGraphEdge[] = [],
  profile: MarkdownProfile = 'public',
): string {
  const outgoing = edges.filter((edge) => edge.source === entity.id);
  const verification = outgoing.filter((edge) => edge.type === 'tested-by');
  const lines = [
    GENERATED_HEADER,
    '',
    `# ${entity.title}`,
    '',
    `ID: \`${entity.id}\``,
    `Kind: \`${entity.kind}\``,
    `Profile: \`${profile}\``,
    '',
    entity.summary,
  ];

  const metadata = renderMetadata(entity);
  if (metadata.length > 0) {
    lines.push('', '## Metadata', '', ...metadata);
  }

  const drillDown = renderLocalDrillDown(entity, edges);
  if (drillDown.length > 0) {
    lines.push('', '## Drill Down', '', ...drillDown);
  }

  if (entity.code?.paths?.length || entity.code?.entrypoints?.length) {
    lines.push('', '## Code', '');
    for (const codePath of entity.code.paths ?? []) {
      lines.push(`- path: \`${codePath}\``);
    }
    for (const entrypoint of entity.code.entrypoints ?? []) {
      lines.push(`- entrypoint: \`${entrypoint}\``);
    }
  }

  if (entity.uri || entity.access) {
    lines.push('', '## Access', '');
    if (entity.uri) {
      lines.push(`- uri: \`${renderUri(entity.uri, profile)}\``);
    }
    if (entity.access?.method) {
      lines.push(`- method: \`${entity.access.method}\``);
    }
    if (profile !== 'public' && entity.access?.server) {
      lines.push(`- server: \`${entity.access.server}\``);
    }
    if (profile !== 'public' && entity.access?.permission) {
      lines.push(`- permission: \`${entity.access.permission}\``);
    }
    if (entity.access?.private_overlay_required || isPrivateUri(entity.uri)) {
      lines.push('- private overlay required');
    }
  }

  lines.push('', '## Relations', '', renderRelationGroups(outgoing));

  if (verification.length > 0) {
    lines.push('', '## Verification', '');
    for (const edge of verification) {
      lines.push(`- \`${edge.target}\``);
    }
  }

  if (entity.agent) {
    lines.push('', '## Agent Hints', '');
    for (const hint of entity.agent.load_when ?? []) {
      lines.push(`- load when: ${hint}`);
    }
    for (const hint of entity.agent.avoid_loading_when ?? []) {
      lines.push(`- avoid when: ${hint}`);
    }
    if (entity.agent.token_budget_hint !== undefined) {
      lines.push(`- token budget hint: ${entity.agent.token_budget_hint}`);
    }
    for (const note of entity.agent.risk_notes ?? []) {
      lines.push(`- risk: ${note}`);
    }
  }

  return `${lines.join('\n')}\n`;
}

function renderRootAtlasView(
  entities: AtlasEntity[],
  edges: AtlasGraphEdge[],
  profile: MarkdownProfile,
): string {
  const graph: AtlasGraph = {
    rootPath: '.',
    entities,
    edges,
    index: createGraphIndex(entities, edges),
    diagnostics: [],
  };
  return `${GENERATED_HEADER}\n\n${renderAtlasOverviewMarkdown(createAtlasOverview(graph, profile))}`;
}

function renderVerificationView(
  entities: AtlasEntity[],
  edges: AtlasGraphEdge[],
  profile: MarkdownProfile,
): string {
  const tests = entities.filter((entity) => entity.kind === 'test-scope');
  const lines = [
    GENERATED_HEADER,
    '',
    '# Verification',
    '',
    `Profile: \`${profile}\``,
    '',
    '## Test Scopes',
    '',
    renderEntityList(tests),
  ];

  for (const test of tests) {
    lines.push('', `## ${test.title}`, '', `ID: \`${test.id}\``, '', test.summary);
    for (const command of test.commands ?? []) {
      lines.push('', `- command: \`${command.command}\``);
      if (command.purpose) {
        lines.push(`  purpose: ${command.purpose}`);
      }
    }

    const verifies = edges.filter((edge) => edge.source === test.id && edge.type === 'verifies');
    if (verifies.length > 0) {
      lines.push('', 'Verifies:');
      for (const edge of verifies) {
        lines.push(`- \`${edge.target}\``);
      }
    }
  }

  return `${lines.join('\n')}\n`;
}

function renderEntityDirectoryIndex(
  kind: AtlasEntityKind,
  entities: AtlasEntity[],
  profile: MarkdownProfile,
): string {
  const title = titleCase(`${kind} index`);
  const lines = [
    GENERATED_HEADER,
    '',
    `# ${title}`,
    '',
    `Profile: \`${profile}\``,
    '',
    `Generated index of visible \`${kind}\` entities.`,
    '',
  ];

  const cliInterfaces = kind === 'interface' ? entities.filter((entity) => isRecord(entity.metadata?.cli)) : [];
  if (cliInterfaces.length > 0) {
    lines.push('## CLI Command Groups', '');
    for (const group of groupCliInterfaceLinks(cliInterfaces)) {
    lines.push(`- ${group.title} (${group.items.length})${group.description ? `: ${group.description} ` : ': '}${group.items.map((item) => `[${item.label}](${item.path})`).join(', ')}`);
    }
    const otherInterfaces = entities.filter((entity) => !isRecord(entity.metadata?.cli));
    if (otherInterfaces.length > 0) {
      lines.push('', '## Other Interfaces', '', ...renderLinkedEntityList(otherInterfaces));
    }
  } else {
    lines.push(...renderLinkedEntityList(entities));
  }

  return `${lines.join('\n')}\n`;
}

function filterEntitiesByProfile(entities: AtlasEntity[], profile: MarkdownProfile): AtlasEntity[] {
  if (profile !== 'public') {
    return [...entities].sort(compareEntities);
  }

  return entities
    .filter((entity) => entity.visibility === undefined || entity.visibility === 'public')
    .sort(compareEntities);
}

function renderMetadata(entity: AtlasEntity): string[] {
  const metadata: string[] = [];
  if (entity.status) {
    metadata.push(`- status: \`${entity.status}\``);
  }
  if (entity.visibility) {
    metadata.push(`- visibility: \`${entity.visibility}\``);
  }
  if (entity.tags?.length) {
    metadata.push(`- tags: ${entity.tags.map((tag) => `\`${tag}\``).join(', ')}`);
  }
  if (entity.owners?.length) {
    metadata.push(`- owners: ${entity.owners.join(', ')}`);
  }
  return metadata;
}

function renderLocalDrillDown(entity: AtlasEntity, edges: AtlasGraphEdge[]): string[] {
  if (isPackageComponent(entity)) {
    return renderPackageDrillDown(entity, edges);
  }

  if (entity.kind !== 'domain' && entity.kind !== 'workflow') {
    return [];
  }

  const lines: string[] = [];
  const workflows = relatedEntities(entity.id, 'contains', 'workflow', edges);
  const capabilities = relatedEntities(entity.id, ['contains', 'uses', 'implements'], 'capability', edges);
  const components = relatedEntities(entity.id, ['contains', 'uses', 'implemented-by'], 'component', edges);
  const documents = relatedEntities(entity.id, 'documented-in', 'document', edges);
  const tests = relatedEntities(entity.id, 'tested-by', 'test-scope', edges);

  if (workflows.length > 0) {
    lines.push('### Workflows', '', ...workflows.map((id) => `- \`${id}\``), '');
  }
  if (capabilities.length > 0) {
    lines.push('### Capabilities', '', ...capabilities.map((id) => `- \`${id}\``), '');
  }
  if (components.length > 0) {
    lines.push('### Components', '', ...components.map((id) => `- \`${id}\``), '');
  }
  if (documents.length > 0) {
    lines.push('### Documents', '', ...documents.map((id) => `- \`${id}\``), '');
  }
  if (tests.length > 0) {
    lines.push('### Tests', '', ...tests.map((id) => `- \`${id}\``));
  }

  return lines.filter((line, index, all) => !(line === '' && all[index - 1] === ''));
}

function renderPackageDrillDown(entity: AtlasEntity, edges: AtlasGraphEdge[]): string[] {
  const lines: string[] = [];
  const metadata = readPackageMetadata(entity);
  const packageFacts = [
    metadata.root ? `root: \`${metadata.root}\`` : undefined,
    metadata.path ? `manifest: \`${metadata.path}\`` : undefined,
    metadata.exports?.length ? `exports: ${metadata.exports.map((item) => `\`${item}\``).join(', ')}` : undefined,
  ].filter((item): item is string => Boolean(item));

  if (packageFacts.length > 0) {
    lines.push('### Package Facts', '', ...packageFacts.map((item) => `- ${item}`), '');
  }
  if (metadata.scripts?.length) {
    lines.push('### Scripts', '', ...metadata.scripts.map((script) => `- \`${script}\``), '');
  }
  appendPackageDrillDownGroup(lines, 'Interfaces', relatedEntities(entity.id, 'contains', 'interface', edges));
  appendPackageDrillDownGroup(lines, 'Components', relatedEntities(entity.id, 'contains', 'component', edges));
  appendPackageDrillDownGroup(lines, 'Documents', relatedEntities(entity.id, 'contains', 'document', edges));
  appendPackageDrillDownGroup(lines, 'Config', relatedEntities(entity.id, 'contains', 'resource', edges));
  appendPackageDrillDownGroup(lines, 'Tests', relatedEntities(entity.id, 'contains', 'test-scope', edges));
  return lines.filter((line, index, all) => !(line === '' && all[index - 1] === ''));
}

function renderPackageReadme(
  entity: AtlasEntity,
  entities: AtlasEntity[],
  edges: AtlasGraphEdge[],
  profile: MarkdownProfile,
): string {
  const metadata = readPackageMetadata(entity);
  const related = collectPackageReadmeRelated(entity, entities, edges);
  const commands = prioritizePackageCommands(entity.commands ?? []);
  const lines = [
    GENERATED_HEADER,
    '',
    `# ${entity.title}`,
    '',
    entity.summary,
    '',
    '## Quick Orientation',
    '',
    `- Package root: \`${metadata.root ?? '.'}\`.`,
    `- Manifest: \`${metadata.path ?? entity.uri ?? 'package.json'}\`.`,
    '- Use this README for package-local orientation; use the repo README and `docs/agents/atlas.md` for cross-package context.',
  ];

  const facts = [
    metadata.exports?.length ? `exports: ${metadata.exports.map((item) => `\`${item}\``).join(', ')}` : undefined,
    metadata.scripts?.length ? `scripts: ${metadata.scripts.map((item) => `\`${item}\``).join(', ')}` : undefined,
  ].filter((item): item is string => Boolean(item));
  if (facts.length > 0) {
    lines.push('', '## Package Facts', '', ...facts.map((fact) => `- ${fact}`));
  }

  const codeFacts = [
    ...(entity.code?.paths ?? []).map((item) => `path: \`${item}\``),
    ...(entity.code?.entrypoints ?? []).map((item) => `entrypoint: \`${item}\``),
  ];
  if (codeFacts.length > 0) {
    lines.push('', '## Code', '', ...codeFacts.map((fact) => `- ${fact}`));
  }

  if (commands.length > 0) {
    lines.push('', '## Normal Use', '');
    for (const command of commands.slice(0, 8)) {
      lines.push(`- \`${command.command}\`${command.purpose ? ` - ${command.purpose}` : ''}`);
    }
  }

  if (related.interfaces.length > 0) {
    lines.push('', '## Interfaces', '', ...related.interfaces.slice(0, 10).map(renderPackageInterfaceReadmeItem));
  }
  if (related.tests.length > 0) {
    lines.push('', '## Verification', '', ...related.tests.slice(0, 6).map((item) => `- \`${item.id}\` - ${item.summary}`));
  }
  if (related.documents.length > 0) {
    lines.push('', '## Docs', '');
    for (const document of related.documents.slice(0, 8)) {
      const target = document.uri && !isPrivateUri(document.uri) ? ` ([source](${renderUri(document.uri, profile)}))` : '';
      lines.push(`- \`${document.id}\` - ${document.title}: ${document.summary}${target}`);
    }
  }

  lines.push('', '## Generated Source', '', '- This package README is generated from Agent Atlas metadata and source-derived package surfaces.');
  return `${lines.join('\n')}\n`;
}

function renderPackageInterfaceReadmeItem(entity: AtlasEntity): string {
  const cli = isRecord(entity.metadata?.cli) ? entity.metadata.cli : undefined;
  const usage = readString(cli?.usage);
  const cliName = readString(cli?.cli_name);
  const command = readString(cli?.command);
  const executable = usage ?? [cliName, command].filter(Boolean).join(' ');
  if (executable) {
    return `- \`${executable}\` - ${entity.summary} (\`${entity.id}\`)`;
  }
  return `- \`${entity.id}\` - ${entity.summary}`;
}

function collectPackageReadmeRelated(
  entity: AtlasEntity,
  entities: AtlasEntity[],
  edges: AtlasGraphEdge[],
): { interfaces: AtlasEntity[]; tests: AtlasEntity[]; documents: AtlasEntity[] } {
  const relatedIds = new Set(
    edges
      .filter((edge) => edge.source === entity.id || edge.target === entity.id)
      .flatMap((edge) => [edge.source, edge.target])
      .filter((id) => id !== entity.id),
  );
  const related = entities.filter((candidate) => relatedIds.has(candidate.id)).sort(compareEntities);
  return {
    interfaces: related.filter((candidate) => candidate.kind === 'interface'),
    tests: related.filter((candidate) => candidate.kind === 'test-scope'),
    documents: related.filter((candidate) => candidate.kind === 'document' && !isAgentSkillDocument(candidate)),
  };
}

function prioritizePackageCommands(commands: NonNullable<AtlasEntity['commands']>): NonNullable<AtlasEntity['commands']> {
  const preferred = ['test', 'build', 'typecheck', 'lint', 'check', 'verify', 'start', 'dev'];
  return [...commands].sort((left, right) => {
    const leftName = left.command.split(/\s+/).at(-1) ?? left.command;
    const rightName = right.command.split(/\s+/).at(-1) ?? right.command;
    return preferredIndex(preferred, leftName) - preferredIndex(preferred, rightName) || left.command.localeCompare(right.command);
  });
}

function appendPackageDrillDownGroup(lines: string[], title: string, ids: AtlasEntityId[]): void {
  if (ids.length === 0) {
    return;
  }
  lines.push(`### ${title}`, '', ...ids.map((id) => `- \`${id}\``), '');
}

function relatedEntities(
  sourceId: AtlasEntityId,
  relationType: string | string[],
  targetKind: AtlasEntityKind,
  edges: AtlasGraphEdge[],
): AtlasEntityId[] {
  const relationTypes = Array.isArray(relationType) ? relationType : [relationType];
  return [
    ...new Set(
      edges
        .filter(
          (edge) =>
            edge.source === sourceId &&
            relationTypes.includes(edge.type) &&
            edge.target.startsWith(`${targetKind}:`),
        )
        .map((edge) => edge.target),
    ),
  ].sort();
}

function renderUri(uri: string, profile: MarkdownProfile): string {
  if (profile === 'public' && isPrivateUri(uri)) {
    return '[redacted: private reference]';
  }

  return uri;
}

function collectReadmeEntities(
  repositoryId: AtlasEntityId | undefined,
  kind: AtlasEntityKind,
  entities: AtlasEntity[],
  edges: AtlasGraphEdge[],
): AtlasEntity[] {
  const candidates = entities.filter((entity) => entity.kind === kind);
  if (!repositoryId) {
    return candidates.sort(compareEntities);
  }

  const relatedIds = new Set(
    edges
      .filter((edge) => edge.source === repositoryId || edge.target === repositoryId)
      .flatMap((edge) => [edge.source, edge.target])
      .filter((id) => id !== repositoryId),
  );
  const directlyRelated = candidates.filter((entity) => relatedIds.has(entity.id));
  return (directlyRelated.length > 0 ? directlyRelated : candidates).sort(compareEntities);
}

function appendReadmeSection(lines: string[], title: string, entities: AtlasEntity[]): void {
  if (entities.length === 0) {
    return;
  }

  lines.push('', `## ${title}`, '');
  for (const entity of entities) {
    const target = entity.uri && !isPrivateUri(entity.uri) ? ` ([source](${entity.uri}))` : '';
    lines.push(`- \`${entity.id}\` - ${entity.title}: ${entity.summary}${target}`);
  }
}

function appendDrillDownSection(lines: string[], documents: AtlasEntity[]): void {
  lines.push('', '## Drill Down', '');
  lines.push('- Atlas overview: `docs/agents/atlas.md`.');
  lines.push('- Task-scoped Atlas navigation: `atlas context-pack "<task>" --path . --budget 4000` or `atlas resolve-path <path> --path .`.');
  lines.push('- Entity indexes: `docs/agents/domains/`, `docs/agents/workflows/`, `docs/agents/components/`, and `docs/agents/capabilities/`.');
  lines.push('- Source-derived inventory: `docs/generated/source-derived-reference.md`.');
  const docsIndex = documents.find((document) => document.uri === 'docs/index.md');
  if (docsIndex?.uri) {
    lines.push(`- Documentation map: [${docsIndex.title}](${docsIndex.uri}).`);
  } else {
    lines.push('- Documentation map: `docs/index.md` when present.');
  }
}

function appendVerificationSection(
  lines: string[],
  tests: AtlasEntity[],
  repositoryCommands: NonNullable<AtlasEntity['commands']>,
): void {
  lines.push('', '## Verification', '');
  const verificationRepositoryCommands = repositoryCommands.filter((command) => /verify|test|check/i.test(command.command));
  const commands = prioritizeVerificationCommands([...verificationRepositoryCommands, ...collectTestCommands(tests)]).slice(0, 8);
  if (commands.length > 0) {
    for (const command of commands) {
      lines.push(`- \`${command.command}\`${command.purpose ? ` - ${command.purpose}` : ''}`);
    }
  } else {
    lines.push('- Use the repo-local test and check scripts advertised by package metadata.');
  }
  lines.push('- Scoped verification map: `docs/agents/verification.md`.');
}

function collectTestCommands(tests: AtlasEntity[]): NonNullable<AtlasEntity['commands']> {
  const seen = new Set<string>();
  const commands: NonNullable<AtlasEntity['commands']> = [];
  for (const command of tests.flatMap((test) => test.commands ?? [])) {
    if (seen.has(command.command)) {
      continue;
    }
    seen.add(command.command);
    commands.push(command);
  }
  return commands;
}

function prioritizeVerificationCommands(
  commands: NonNullable<AtlasEntity['commands']>,
): NonNullable<AtlasEntity['commands']> {
  const seen = new Set<string>();
  return [...commands]
    .sort((left, right) => verificationCommandRank(left.command) - verificationCommandRank(right.command))
    .filter((command) => {
      if (seen.has(command.command)) return false;
      seen.add(command.command);
      return true;
    });
}

function verificationCommandRank(command: string): number {
  if (/\bverify:session\b/.test(command)) return 0;
  if (/verify/i.test(command)) return 1;
  if (/test/i.test(command)) return 2;
  if (/check/i.test(command)) return 3;
  return 4;
}

function isAgentSkillDocument(entity: AtlasEntity): boolean {
  return Boolean(entity.uri && /^\.agents\/skills\/[^/]+\/SKILL\.md$/i.test(entity.uri));
}

function collectReadmeCommands(
  repository: AtlasEntity | undefined,
  tests: AtlasEntity[],
): NonNullable<AtlasEntity['commands']> {
  const seen = new Set<string>();
  const commands: NonNullable<AtlasEntity['commands']> = [];
  for (const command of [...(repository?.commands ?? []), ...tests.flatMap((test) => test.commands ?? [])]) {
    if (seen.has(command.command)) {
      continue;
    }
    seen.add(command.command);
    commands.push(command);
  }
  return commands.slice(0, 10);
}

function collectReadmeCliInterfaces(
  repositoryId: AtlasEntityId | undefined,
  entities: AtlasEntity[],
  edges: AtlasGraphEdge[],
): AtlasEntity[] {
  const cliInterfaces = entities.filter((entity) => entity.kind === 'interface' && isRecord(entity.metadata?.cli));
  if (!repositoryId || cliInterfaces.length === 0) {
    return cliInterfaces.sort(compareCliInterfaces);
  }

  const relatedIds = new Set(
    edges
      .filter((edge) => edge.source === repositoryId || edge.target === repositoryId)
      .flatMap((edge) => [edge.source, edge.target])
      .filter((id) => id !== repositoryId),
  );
  const directlyRelated = cliInterfaces.filter((entity) => relatedIds.has(entity.id));
  return (directlyRelated.length > 0 ? directlyRelated : cliInterfaces).sort(compareCliInterfaces);
}

function humanRepositorySummary(repository: AtlasEntity | undefined): string {
  const title = repository?.title ?? 'This repository';
  const rawSummary = repository?.summary?.trim();
  if (rawSummary && new RegExp(`^${escapeRegExp(title)}\\s+is\\b`, 'i').test(rawSummary)) {
    return sentenceFromSummary(rawSummary);
  }
  const summary = summaryFragment(rawSummary ?? 'the capabilities described below');
  return `${title} is ${summaryWithArticle(summary)}.`;
}

function buildDefaultQuickOrientation(
  docsIndex: AtlasEntity | undefined,
  cliGroups: CliInterfaceGroup[],
  cliReference: ReadmeLinkItem | undefined,
): string[] {
  const lines: string[] = [];
  if (cliGroups.length > 0) {
    lines.push(
      `Most repo workflows are exposed through the CLI overview below${cliReference ? `, with exact syntax in [${cliReference.label}](${cliReference.path})` : ''}.`,
    );
  }
  if (docsIndex?.uri) {
    lines.push(`Use [${docsIndex.title}](${docsIndex.uri}) as the documentation map for deeper architecture and operating-model context.`);
  }
  lines.push('This README is generated; update Atlas metadata or referenced canonical docs instead of editing it directly.');
  return lines;
}

function appendGeneratedOverviewSection(
  lines: string[],
  readmeMetadata: RepositoryReadmeMetadata,
  repository: AtlasEntity | undefined,
  workflows: AtlasEntity[],
  components: AtlasEntity[],
  cliGroups: CliInterfaceGroup[],
): void {
  const hasConfiguredOverview = readmeMetadata.sections?.some((section) => section.title.toLowerCase() === 'what this repo does');
  if (hasConfiguredOverview) {
    return;
  }
  const rankedWorkflows = rankReadmeOverviewEntities(workflows, repository?.summary ?? '');
  const rankedComponents = rankReadmeOverviewEntities(components, repository?.summary ?? '');
  const items = [
    ...rankedWorkflows.slice(0, 6).map((workflow) => sentenceFromSummary(workflow.summary)),
    ...rankedComponents.slice(0, Math.max(0, 6 - rankedWorkflows.length)).map((component) => sentenceFromSummary(component.summary)),
  ];
  if (items.length === 0 && cliGroups.length > 0) {
    items.push(...cliGroups.slice(0, 6).map((group) => `${group.title}: ${group.description ?? 'Command group exposed by the generated CLI catalog.'}`));
  }
  appendReadmeTextSection(lines, 'What This Repo Does', items);
}

function appendNormalUseSection(
  lines: string[],
  readmeMetadata: RepositoryReadmeMetadata,
  sessionStart: { command: string; purpose?: string } | undefined,
  cliGroups: CliInterfaceGroup[],
  tests: AtlasEntity[],
  commands: NonNullable<AtlasEntity['commands']>,
): void {
  const configuredNormalUse = readmeMetadata.sections?.some((section) => section.title.toLowerCase() === 'normal use');
  if (configuredNormalUse) {
    return;
  }
  const items: string[] = [];
  if (sessionStart) {
    items.push(`Start with \`${sessionStart.command}\`${sessionStart.purpose ? ` to ${lowercaseFirst(sessionStart.purpose)}` : ' for repo orientation'}.`);
  }
  if (cliGroups.length > 0) {
    const cliInvocation = inferCliInvocation(cliGroups) ?? 'the repo CLI';
    items.push(`Use \`${cliInvocation}${cliInvocation === 'the repo CLI' ? '' : ' <command>'}\` for the repo-supported workflows listed in the command groups below.`);
  }
  const verificationCommand =
    commands.find((command) => /\bverify:session\b/.test(command.command)) ??
    commands.find((command) => /verify/i.test(command.command)) ??
    collectTestCommands(tests)[0] ??
    commands.find((command) => /test|check/i.test(command.command));
  if (verificationCommand) {
    items.push(`Verify meaningful changes with \`${verificationCommand.command}\`${verificationCommand.purpose ? ` to ${lowercaseFirst(verificationCommand.purpose)}` : ''}.`);
  }
  appendReadmeTextSection(lines, 'Normal Use', items);
}

function rankReadmeOverviewEntities(entities: AtlasEntity[], repositorySummary: string): AtlasEntity[] {
  const summaryTerms = new Set(significantTerms(repositorySummary));
  return [...entities].sort((left, right) => {
    const rightScore = overviewEntityScore(right, summaryTerms);
    const leftScore = overviewEntityScore(left, summaryTerms);
    return rightScore - leftScore || left.title.localeCompare(right.title);
  });
}

function overviewEntityScore(entity: AtlasEntity, summaryTerms: Set<string>): number {
  const entityTerms = significantTerms(`${entity.title} ${entity.summary}`);
  return entityTerms.filter((term) => summaryTerms.has(term)).length;
}

function significantTerms(value: string): string[] {
  const stopWords = new Set(['and', 'for', 'from', 'into', 'the', 'with', 'this', 'that', 'repo', 'repository']);
  return value
    .toLowerCase()
    .split(/[^a-z0-9]+/g)
    .filter((term) => term.length >= 4 && !stopWords.has(term));
}

function collectDefaultKeyDocs(documents: AtlasEntity[], cliReference: ReadmeLinkItem | undefined): ReadmeLinkItem[] | undefined {
  const candidates = [
    findDocumentLink(documents, 'docs/index.md', 'Documentation map and deeper docs entrypoint.'),
    cliReference,
    findDocumentByPathPattern(documents, /docs\/(vision|principles|non-goals|architecture|concepts)\b/i, 'Project direction, architecture, or scope context.'),
    findDocumentByPathPattern(documents, /coding-standard/i, 'Default coding or contribution standard.'),
    findDocumentLink(documents, 'AGENTS.md', 'Repo-local operating instructions and agent guidance.'),
  ].filter((item): item is ReadmeLinkItem => Boolean(item));
  const deduped = dedupeLinkItems(candidates);
  return deduped.length > 0 ? deduped : undefined;
}

function findSessionStartCommand(
  commands: NonNullable<AtlasEntity['commands']>,
  cliGroups: CliInterfaceGroup[],
): { command: string; purpose?: string } | undefined {
  const repositoryCommand = commands.find((command) => /session:start\b/.test(command.command));
  if (repositoryCommand) {
    return repositoryCommand;
  }
  const cliCommand = cliGroups.flatMap((group) => group.commands).find((command) => /session:start\b/.test(command));
  return cliCommand ? { command: cliCommand } : undefined;
}

function inferCliInvocation(cliGroups: CliInterfaceGroup[]): string | undefined {
  const label = cliGroups.flatMap((group) => group.commands)[0];
  if (!label) {
    return undefined;
  }
  const parts = label.split(/\s+/).filter(Boolean);
  if (parts.length === 0) {
    return undefined;
  }
  return /^(pnpm|npm|yarn|bun)$/.test(parts[0]) && parts[1] ? `${parts[0]} ${parts[1]}` : parts[0];
}

function collectDefaultDurableState(entities: AtlasEntity[]): ReadmePathItem[] | undefined {
  const paths = new Map<string, string>();
  for (const entity of entities) {
    for (const pathValue of collectEntityPaths(entity)) {
      const root = durableRootForPath(pathValue);
      if (root) {
        paths.set(root.path, paths.get(root.path) ?? root.note ?? '');
      }
    }
  }
  const preferredOrder = ['.agent-atlas/', 'docs/agents/', 'docs/generated/', 'registry/', '.agents/skills/', 'evals/', '.runtime/', 'packages/'];
  const items = [...paths.entries()].map(([pathValue, note]) => ({ path: pathValue, note }));
  items.sort((left, right) => preferredIndex(preferredOrder, left.path) - preferredIndex(preferredOrder, right.path) || left.path.localeCompare(right.path));
  return items.slice(0, 8).length > 0 ? items.slice(0, 8) : undefined;
}

function collectEntityPaths(entity: AtlasEntity): string[] {
  return [entity.uri, ...(entity.code?.paths ?? []), ...(entity.code?.entrypoints ?? [])].filter((pathValue): pathValue is string => Boolean(pathValue));
}

function durableRootForPath(pathValue: string): ReadmePathItem | undefined {
  const normalized = pathValue.replaceAll('\\', '/');
  const root = normalized.split('/')[0];
  if (normalized.startsWith('.agent-atlas/')) return { path: '.agent-atlas/', note: 'Canonical Atlas metadata and overlays.' };
  if (normalized.startsWith('docs/agents/')) return { path: 'docs/agents/', note: 'Generated Atlas Markdown views.' };
  if (normalized.startsWith('docs/generated/')) return { path: 'docs/generated/', note: 'Generated references and inventories.' };
  if (normalized.startsWith('registry/')) return { path: 'registry/', note: 'Registry and tracked operational definitions.' };
  if (normalized.startsWith('.agents/skills/')) return { path: '.agents/skills/', note: 'Reusable agent workflows.' };
  if (normalized.startsWith('evals/')) return { path: 'evals/', note: 'Workflow protections and regression checks.' };
  if (normalized.startsWith('.runtime/')) return { path: '.runtime/', note: 'Generated runtime and current-state artifacts.' };
  if (normalized.startsWith('packages/')) return { path: 'packages/', note: 'Workspace packages and implementation surfaces.' };
  if (normalized.startsWith('apps/')) return { path: 'apps/', note: 'Application and CLI entrypoint surfaces.' };
  if (normalized.startsWith('docs/')) return { path: 'docs/', note: 'Human-authored documentation.' };
  if (normalized.startsWith('examples/')) return { path: 'examples/', note: 'Examples and sample fixtures.' };
  if (normalized.startsWith('scripts/')) return { path: 'scripts/', note: 'Repository helper scripts.' };
  return undefined;
}

function findDocumentLink(documents: AtlasEntity[], pathValue: string, note: string): ReadmeLinkItem | undefined {
  const document = documents.find((entity) => entity.uri === pathValue);
  return document?.uri ? { label: document.title, path: document.uri, note } : undefined;
}

function findDocumentByPathPattern(documents: AtlasEntity[], pattern: RegExp, note: string): ReadmeLinkItem | undefined {
  const document = documents.find((entity) => Boolean(entity.uri && pattern.test(entity.uri)));
  return document?.uri && !isPrivateUri(document.uri) ? { label: document.title, path: document.uri, note } : undefined;
}

function dedupeLinkItems(items: ReadmeLinkItem[]): ReadmeLinkItem[] {
  const seen = new Set<string>();
  return items.filter((item) => {
    if (seen.has(item.path)) return false;
    seen.add(item.path);
    return true;
  });
}

function preferredIndex(order: string[], value: string): number {
  const index = order.indexOf(value);
  return index === -1 ? Number.MAX_SAFE_INTEGER : index;
}

function lowercaseFirst(value: string): string {
  return value.length > 0 ? `${value.charAt(0).toLowerCase()}${value.slice(1).replace(/\.$/, '')}` : value;
}

function uppercaseFirst(value: string): string {
  return value.length > 0 ? `${value.charAt(0).toUpperCase()}${value.slice(1)}` : value;
}

function summaryFragment(value: string): string {
  return lowercaseFirst(value.trim());
}

function summaryWithArticle(value: string): string {
  if (/^(a|an|the)\s/i.test(value)) {
    return value;
  }
  return /^[aeiou]/i.test(value) ? `an ${value}` : `a ${value}`;
}

function sentenceFromSummary(value: string): string {
  const trimmed = value.trim();
  if (trimmed.length === 0) {
    return trimmed;
  }
  return /[.!?]$/.test(trimmed) ? trimmed : `${trimmed}.`;
}

function readRepositoryReadmeMetadata(repository: AtlasEntity | undefined): RepositoryReadmeMetadata {
  const metadata = isRecord(repository?.metadata) ? repository?.metadata : undefined;
  const readme = isRecord(metadata?.readme) ? metadata?.readme : undefined;
  return {
    start_here: readStringArray(readme?.start_here),
    overview: readStringArray(readme?.overview),
    current_truth_order: readStringArray(readme?.current_truth_order),
    key_docs: readLinkItems(readme?.key_docs),
    durable_state: readPathItems(readme?.durable_state),
    operational_notes: readStringArray(readme?.operational_notes),
    sections: readSections(readme?.sections),
    cli: readCliMetadata(readme?.cli),
  };
}

function appendReadmeTextSection(lines: string[], title: string, items: string[] | undefined): void {
  if (!items?.length) {
    return;
  }
  lines.push('', `## ${title}`, '', ...renderReadmeList(items));
}

function appendReadmeLinkSection(lines: string[], title: string, items: ReadmeLinkItem[] | undefined): void {
  if (!items?.length) {
    return;
  }
  lines.push('', `## ${title}`, '');
  for (const item of items) {
    lines.push(`- [${item.label}](${item.path})${item.note ? ` - ${item.note}` : ''}`);
  }
}

function appendReadmePathSection(lines: string[], title: string, items: ReadmePathItem[] | undefined): void {
  if (!items?.length) {
    return;
  }
  lines.push('', `## ${title}`, '');
  for (const item of items) {
    lines.push(`- \`${item.path}\`${item.note ? ` - ${item.note}` : ''}`);
  }
}

function appendConfiguredSections(lines: string[], sections: ReadmeSection[] | undefined): void {
  for (const section of sections ?? []) {
    appendReadmeTextSection(lines, section.title, section.items);
  }
}

function appendCommonEntryPointsSection(lines: string[], cliGroups: CliInterfaceGroup[]): void {
  const entryPoints = rankCliEntryPoints(cliGroups).slice(0, 8);
  if (entryPoints.length === 0) {
    return;
  }

  lines.push('', '## Common Entry Points', '', '| Task | Command |', '| --- | --- |');
  for (const item of entryPoints) {
    lines.push(`| ${escapeMarkdownTableCell(commandTaskLabel(item))} | \`${item.label}\` |`);
  }
}

function appendCliSection(
  lines: string[],
  cliMetadata: ReadmeCliMetadata | undefined,
  reference: ReadmeLinkItem | undefined,
  interfaceGroups: CliInterfaceGroup[],
): void {
  if (!cliMetadata?.overview?.length && !reference && interfaceGroups.length === 0) {
    return;
  }

  lines.push('', '## CLI', '');
  if (cliMetadata?.overview?.length) {
    lines.push(...renderReadmeList(cliMetadata.overview), '');
  }
  if (reference) {
    lines.push(`- Full command reference: [${reference.label}](${reference.path})${reference.note ? ` - ${reference.note}` : ''}`);
  }

  if (interfaceGroups.length > 0) {
    lines.push('', '### Command Groups', '', '| Group | Purpose | Example |', '| --- | --- | --- |');
  }
  for (const group of interfaceGroups) {
    const shownCommands = group.commands.slice(0, README_CLI_GROUP_COMMAND_LIMIT);
    const hiddenCount = group.commands.length - shownCommands.length;
    const groupLabel = reference
      ? `[${group.title}](${reference.path}#${githubHeadingAnchor(group.title)})`
      : group.title;
    const commandSummary = [
      ...shownCommands.map((command) => `\`${command}\``),
      ...(hiddenCount > 0 ? [`+${hiddenCount} more`] : []),
    ].join(' ');
    lines.push(
      `| ${groupLabel} (${group.commands.length}) | ${escapeMarkdownTableCell(group.description ?? 'See the command reference for details.')} | ${commandSummary} |`,
    );
  }
}

function githubHeadingAnchor(title: string): string {
  return title
    .trim()
    .toLowerCase()
    .replace(/`/g, '')
    .replace(/&/g, 'and')
    .replace(/[^a-z0-9 -]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-');
}

function escapeMarkdownTableCell(value: string): string {
  return value.replace(/\|/g, '\\|').replace(/\r?\n/g, ' ');
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function renderReadmeList(items: string[]): string[] {
  return items.map((item) => `- ${item}`);
}

function readStringArray(value: unknown): string[] | undefined {
  if (!Array.isArray(value)) {
    return undefined;
  }
  const strings = value.filter((item): item is string => typeof item === 'string' && item.trim().length > 0);
  return strings.length > 0 ? strings : undefined;
}

function readLinkItems(value: unknown): ReadmeLinkItem[] | undefined {
  if (!Array.isArray(value)) {
    return undefined;
  }
  const items: ReadmeLinkItem[] = [];
  for (const item of value) {
    if (!isRecord(item)) {
      continue;
    }
    const label = readString(item.label);
    const pathValue = readString(item.path);
    if (!label || !pathValue) {
      continue;
    }
    const note = readString(item.note);
    items.push(note ? { label, path: pathValue, note } : { label, path: pathValue });
  }
  return items.length > 0 ? items : undefined;
}

function readPathItems(value: unknown): ReadmePathItem[] | undefined {
  if (!Array.isArray(value)) {
    return undefined;
  }
  const items: ReadmePathItem[] = [];
  for (const item of value) {
    if (!isRecord(item)) {
      continue;
    }
    const pathValue = readString(item.path);
    if (!pathValue) {
      continue;
    }
    const note = readString(item.note);
    items.push(note ? { path: pathValue, note } : { path: pathValue });
  }
  return items.length > 0 ? items : undefined;
}

function readSections(value: unknown): ReadmeSection[] | undefined {
  if (!Array.isArray(value)) {
    return undefined;
  }
  const sections = value
    .filter(isRecord)
    .map((item) => ({
      title: readString(item.title),
      items: readStringArray(item.items),
    }))
    .filter((item): item is ReadmeSection => Boolean(item.title && item.items?.length));
  return sections.length > 0 ? sections : undefined;
}

function readCliMetadata(value: unknown): ReadmeCliMetadata | undefined {
  if (!isRecord(value)) {
    return undefined;
  }
  const cli: ReadmeCliMetadata = {
    overview: readStringArray(value.overview),
    reference: readLinkItems(value.reference ? [value.reference] : undefined)?.[0],
  };
  return cli.overview?.length || cli.reference ? cli : undefined;
}

function findCliReference(documents: AtlasEntity[]): ReadmeLinkItem | undefined {
  const document = documents.find(
    (entity) =>
      entity.id.includes('cli-command-reference') ||
      entity.uri === 'docs/generated/cli-command-reference.md' ||
      entity.title.toLowerCase().includes('cli command reference'),
  );
  if (!document?.uri || isPrivateUri(document.uri)) {
    return undefined;
  }
  return {
    label: document.title,
    path: document.uri,
    note: document.summary,
  };
}

function groupCliInterfaces(interfaces: AtlasEntity[]): CliInterfaceGroup[] {
  const groups = new Map<string, { description?: string; commands: string[]; items: CliInterfaceItem[] }>();
  for (const entity of interfaces) {
    const cli = isRecord(entity.metadata?.cli) ? entity.metadata.cli : undefined;
    const cliName = readString(cli?.cli_name);
    const command = readString(cli?.command);
    const label = [cliName, command].filter(Boolean).join(' ') || entity.title;
    const group = normalizeCliGroupTitle(readString(cli?.group) ?? 'CLI Commands');
    const current = groups.get(group) ?? { commands: [], items: [] };
    current.description = current.description ?? readString(cli?.group_description) ?? readString(cli?.group_summary);
    current.commands.push(label);
    current.items.push({
      label,
      command: command ?? label,
      summary: readString(cli?.description) ?? entity.summary,
      importance: readString(cli?.importance),
      lifecycle: readStringList(cli?.lifecycle) ?? inferCliLifecycle(`${command ?? ''} ${group} ${entity.summary}`),
      audience: readStringList(cli?.audience) ?? ['human', 'agent'],
      tasks: readStringList(cli?.tasks) ?? [entity.summary],
    });
    groups.set(group, current);
  }

  return [...groups.entries()]
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([title, group]) => ({
      title,
      description: group.description,
      commands: [...new Set(group.commands)].sort((left, right) => left.localeCompare(right)),
      items: dedupeCliItems(group.items).sort((left, right) => left.label.localeCompare(right.label)),
    }));
}

function groupCliInterfaceLinks(
  interfaces: AtlasEntity[],
): Array<{ title: string; description?: string; items: Array<{ label: string; path: string }> }> {
  const groups = new Map<string, { description?: string; items: Array<{ label: string; path: string }> }>();
  for (const entity of interfaces) {
    const cli = isRecord(entity.metadata?.cli) ? entity.metadata.cli : undefined;
    const cliName = readString(cli?.cli_name);
    const command = readString(cli?.command);
    const label = [cliName, command].filter(Boolean).join(' ') || entity.title;
    const group = normalizeCliGroupTitle(readString(cli?.group) ?? 'CLI Commands');
    const current = groups.get(group) ?? { items: [] };
    current.description = current.description ?? readString(cli?.group_description) ?? readString(cli?.group_summary);
    if (!current.items.some((item) => item.label === label)) {
      current.items.push({ label, path: `${entitySlug(entity.id)}.md` });
    }
    groups.set(group, current);
  }

  return [...groups.entries()]
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([title, group]) => ({
      title,
      description: group.description,
      items: group.items.sort((left, right) => left.label.localeCompare(right.label)),
    }));
}

function rankCliEntryPoints(groups: CliInterfaceGroup[]): CliInterfaceItem[] {
  return groups
    .flatMap((group) => group.items.map((item) => ({ ...item, groupTitle: group.title })))
    .filter((item) => item.importance !== 'internal')
    .sort((left, right) => cliEntryPointScore(right) - cliEntryPointScore(left) || left.label.localeCompare(right.label));
}

function cliEntryPointScore(item: CliInterfaceItem & { groupTitle?: string }): number {
  const text = `${item.command} ${item.label} ${item.groupTitle ?? ''} ${item.summary}`.toLowerCase();
  const commandText = `${item.command} ${item.label}`.toLowerCase();
  const importanceScore: Record<string, number> = {
    primary: 100,
    common: 80,
    specialist: 20,
    maintenance: 10,
    internal: -100,
  };
  let score = importanceScore[item.importance ?? ''] ?? 40;
  if (item.lifecycle.includes('orient')) score += 18;
  if (item.lifecycle.includes('verify')) score += 14;
  if (item.lifecycle.includes('plan')) score += 10;
  if (item.lifecycle.includes('maintain')) score -= 8;
  if (/(^|\s)(session:start|context-pack|resolve-path|project:status|verify:session)(\s|$)/.test(commandText)) score += 30;
  if (/\b(overview|doctor|validate|maintain:check|maintain check)\b/.test(commandText)) score += 12;
  if (/\b(generate|docs|migrate|benchmark|proposal|apply|fix|record|ingest)\b/.test(text)) score -= 16;
  return score;
}

function commandTaskLabel(item: CliInterfaceItem): string {
  const task = item.tasks[0] ?? item.summary;
  const normalizedTask = task.replace(/^to\s+/i, '');
  const label = isCommandLikeTask(normalizedTask, item.command)
    ? humanizeCommandTask(item.command)
    : normalizedTask;
  return sentenceFromSummary(uppercaseFirst(label));
}

function isCommandLikeTask(task: string, command: string): boolean {
  const normalizedTask = task.toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim();
  const normalizedCommand = command.toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim();
  return normalizedTask.length > 0 && normalizedTask === normalizedCommand;
}

function humanizeCommandTask(command: string): string {
  const tokens = command.toLowerCase().split(/[^a-z0-9]+/g).filter(Boolean);
  if (tokens.length === 0) {
    return 'Run command';
  }
  if (tokens[0] === 'session' && tokens[1] === 'start') return 'start a repo session';
  if (tokens[0] === 'verify' && tokens[1] === 'session') return 'run session verification';
  if (tokens[0] === 'project' && tokens[1] === 'status') return 'read project status';
  if (tokens.at(-1) === 'record') return `record ${tokens.slice(0, -1).join(' ')}`;
  if (tokens[0] === 'check' || tokens.at(-1) === 'check') return `check ${tokens.filter((token) => token !== 'check').join(' ')}`;
  if (tokens[0] === 'sync' || tokens.at(-1) === 'sync') return `sync ${tokens.filter((token) => token !== 'sync').join(' ')}`;
  if (tokens[0] === 'create' || tokens.at(-1) === 'create') return `create ${tokens.filter((token) => token !== 'create').join(' ')}`;
  if (tokens[0] === 'launch' || tokens.at(-1) === 'launch') return `launch ${tokens.filter((token) => token !== 'launch').join(' ')}`;
  return `run ${tokens.join(' ')}`;
}

function dedupeCliItems(items: CliInterfaceItem[]): CliInterfaceItem[] {
  const byLabel = new Map<string, CliInterfaceItem>();
  for (const item of items) {
    byLabel.set(item.label, item);
  }
  return [...byLabel.values()];
}

function inferCliLifecycle(text: string): string[] {
  const normalized = text.toLowerCase();
  const lifecycle: string[] = [];
  if (/\b(status|show|list|overview|resolve|context|inspect|doctor|preview|diff|discover)\b/.test(normalized)) lifecycle.push('orient');
  if (/\b(plan|proposal|propose|packet|contract)\b/.test(normalized)) lifecycle.push('plan');
  if (/\b(start|run|launch|apply|create|record|sync|ingest|serve)\b/.test(normalized)) lifecycle.push('execute');
  if (/\b(verify|validate|test|check|lint|smoke)\b/.test(normalized)) lifecycle.push('verify');
  if (/\b(maintain|maintenance|generate|generated|docs|refresh|migrate|fix|benchmark|evaluate)\b/.test(normalized)) lifecycle.push('maintain');
  return lifecycle.length > 0 ? [...new Set(lifecycle)] : ['execute'];
}

function normalizeCliGroupTitle(group: string): string {
  return group.replace(/:+$/g, '').trim() || 'CLI Commands';
}

function compareCliInterfaces(left: AtlasEntity, right: AtlasEntity): number {
  const leftCli = isRecord(left.metadata?.cli) ? left.metadata.cli : undefined;
  const rightCli = isRecord(right.metadata?.cli) ? right.metadata.cli : undefined;
  const leftGroup = readString(leftCli?.group) ?? '';
  const rightGroup = readString(rightCli?.group) ?? '';
  const groupCompare = leftGroup.localeCompare(rightGroup);
  if (groupCompare !== 0) return groupCompare;
  return left.id.localeCompare(right.id);
}

function readString(value: unknown): string | undefined {
  return typeof value === 'string' && value.trim().length > 0 ? value : undefined;
}

function readStringList(value: unknown): string[] | undefined {
  if (!Array.isArray(value)) {
    return undefined;
  }
  const strings = value.filter((item): item is string => typeof item === 'string' && item.trim().length > 0);
  return strings.length > 0 ? strings : undefined;
}

function isPackageComponent(entity: AtlasEntity): boolean {
  return entity.kind === 'component' && isRecord(entity.metadata?.package);
}

function readPackageMetadata(entity: AtlasEntity): {
  path?: string;
  root?: string;
  scripts?: string[];
  exports?: string[];
} {
  const packageMetadata = isRecord(entity.metadata?.package) ? entity.metadata.package : {};
  return {
    path: readString(packageMetadata.path),
    root: readString(packageMetadata.root),
    scripts: readStringList(packageMetadata.scripts),
    exports: readStringList(packageMetadata.exports),
  };
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function isPrivateUri(uri: string | undefined): boolean {
  if (!uri) {
    return false;
  }

  const lowerUri = uri.toLowerCase();
  return (
    ['notion:', 'confluence:', 'jira:', 'gdrive:', 'google-drive:', 'gcal:', 'slack:', 'mailto:'].some(
      (scheme) => lowerUri.startsWith(scheme),
    ) ||
    lowerUri.includes('localhost') ||
    /^https?:\/\/(10\.|127\.|192\.168\.|172\.(1[6-9]|2\d|3[0-1])\.)/.test(lowerUri)
  );
}

function renderRelationGroups(edges: AtlasGraphEdge[]): string {
  if (edges.length === 0) {
    return '- No relations declared.';
  }

  const grouped = new Map<string, AtlasGraphEdge[]>();
  for (const edge of edges) {
    const group = grouped.get(edge.type) ?? [];
    group.push(edge);
    grouped.set(edge.type, group);
  }

  return [...grouped.entries()]
    .sort(([left], [right]) => left.localeCompare(right))
    .flatMap(([type, group]) => [
      `### \`${type}\``,
      '',
      ...group.map((edge) => `- \`${edge.target}\`${edge.provenance === 'generated' ? ' _(generated)_' : ''}`),
      '',
    ])
    .join('\n')
    .trimEnd();
}

function renderEntityList(entities: AtlasEntity[]): string {
  if (entities.length === 0) {
    return '- None.';
  }

  return entities
    .sort(compareEntities)
    .map((entity) => `- \`${entity.id}\` - ${entity.title}: ${entity.summary}`)
    .join('\n');
}

function renderLinkedEntityList(entities: AtlasEntity[]): string[] {
  if (entities.length === 0) {
    return ['- None.'];
  }

  return entities
    .sort(compareEntities)
    .map((entity) => `- [${entity.title}](${entitySlug(entity.id)}.md) - \`${entity.id}\`: ${entity.summary}`);
}

function entitySlug(id: AtlasEntityId): string {
  return id.slice(id.indexOf(':') + 1).replaceAll('/', '__');
}

function compareEntities(left: AtlasEntity, right: AtlasEntity): number {
  const kindCompare = left.kind.localeCompare(right.kind);
  if (kindCompare !== 0) return kindCompare;
  return left.id.localeCompare(right.id);
}

function titleCase(value: string): string {
  return value.replace(/\b[a-z]/g, (letter) => letter.toUpperCase());
}
