import type { AtlasEntity, AtlasEntityId, AtlasEntityKind } from '@agent-atlas/schema';
import {
  createAtlasOverview,
  createGraphIndex,
  renderAtlasOverviewMarkdown,
  type AtlasGraph,
  type AtlasGraphEdge,
} from '@agent-atlas/core';
import type { AtlasProfile } from '@agent-atlas/core';

export type MarkdownProfile = AtlasProfile;

export interface MarkdownGenerationOptions {
  profile?: MarkdownProfile;
}

export interface GeneratedMarkdownFile {
  path: string;
  content: string;
}

interface ReadmeLinkItem {
  label: string;
  path: string;
  note?: string;
}

interface ReadmePathItem {
  path: string;
  note?: string;
}

interface ReadmeSection {
  title: string;
  items: string[];
}

interface ReadmeCliMetadata {
  overview?: string[];
  reference?: ReadmeLinkItem;
}

interface CliInterfaceGroup {
  title: string;
  description?: string;
  commands: string[];
}

interface RepositoryReadmeMetadata {
  start_here?: string[];
  current_truth_order?: string[];
  key_docs?: ReadmeLinkItem[];
  durable_state?: ReadmePathItem[];
  operational_notes?: string[];
  sections?: ReadmeSection[];
  cli?: ReadmeCliMetadata;
}

const GENERATED_HEADER = '<!-- Generated by Agent Atlas. Do not edit directly. -->';
const README_CLI_GROUP_COMMAND_LIMIT = 1;

const CARD_KIND_DIRECTORIES: Partial<Record<AtlasEntityKind, string>> = {
  domain: 'domains',
  workflow: 'workflows',
  component: 'components',
  capability: 'capabilities',
  interface: 'interfaces',
  resource: 'resources',
  document: 'documents',
};

export function generateMarkdownViews(
  graph: AtlasGraph,
  options: MarkdownGenerationOptions = {},
): GeneratedMarkdownFile[] {
  const profile = options.profile ?? 'public';
  const entities = filterEntitiesByProfile(graph.entities, profile);
  const entityIds = new Set(entities.map((entity) => entity.id));
  const edges = graph.edges.filter((edge) => entityIds.has(edge.source) && entityIds.has(edge.target));
  const files: GeneratedMarkdownFile[] = [
    {
      path: 'atlas.md',
      content: renderRootAtlasView(entities, edges, profile),
    },
    {
      path: 'verification.md',
      content: renderVerificationView(entities, edges, profile),
    },
  ];

  for (const entity of entities) {
    const directory = CARD_KIND_DIRECTORIES[entity.kind];
    if (!directory) {
      continue;
    }

    files.push({
      path: `${directory}/${entitySlug(entity.id)}.md`,
      content: renderEntityCard(entity, edges, profile),
    });
  }

  for (const [kind, directory] of Object.entries(CARD_KIND_DIRECTORIES) as Array<[AtlasEntityKind, string]>) {
    const directoryEntities = entities.filter((entity) => entity.kind === kind);
    if (directoryEntities.length === 0) {
      continue;
    }
    files.push({
      path: `${directory}/index.md`,
      content: renderEntityDirectoryIndex(kind, directoryEntities, profile),
    });
  }

  return files.sort((left, right) => left.path.localeCompare(right.path));
}

export function renderRepositoryReadme(
  graph: AtlasGraph,
  options: MarkdownGenerationOptions = {},
): string {
  const profile = options.profile ?? 'public';
  const entities = filterEntitiesByProfile(graph.entities, profile);
  const entityIds = new Set(entities.map((entity) => entity.id));
  const edges = graph.edges.filter((edge) => entityIds.has(edge.source) && entityIds.has(edge.target));
  const repository = entities.find((entity) => entity.kind === 'repository');
  const title = repository?.title ?? 'Repository';
  const summary = repository?.summary ?? 'Atlas-generated repository orientation.';
  const domains = collectReadmeEntities(undefined, 'domain', entities, edges).slice(0, 6);
  const workflows = collectReadmeEntities(repository?.id, 'workflow', entities, edges).slice(0, 8);
  const components = collectReadmeEntities(repository?.id, 'component', entities, edges)
    .filter((entity) => !isPackageComponent(entity))
    .slice(0, 10);
  const allDocuments = collectReadmeEntities(repository?.id, 'document', entities, edges)
    .filter((entity) => !isAgentSkillDocument(entity));
  const globalDocuments = entities
    .filter((entity) => entity.kind === 'document')
    .filter((entity) => !isAgentSkillDocument(entity));
  const documents = allDocuments.slice(0, 8);
  const tests = collectReadmeEntities(repository?.id, 'test-scope', entities, edges).slice(0, 8);
  const commands = collectReadmeCommands(repository, tests);
  const cliInterfaces = collectReadmeCliInterfaces(repository?.id, entities, edges);
  const readmeMetadata = readRepositoryReadmeMetadata(repository);
  const docsIndex = allDocuments.find((document) => document.uri === 'docs/index.md');
  const cliReference = readmeMetadata.cli?.reference ?? findCliReference(allDocuments) ?? findCliReference(globalDocuments);
  const cliGroups = groupCliInterfaces(cliInterfaces);
  const defaultKeyDocs = collectDefaultKeyDocs([...allDocuments, ...globalDocuments], cliReference);
  const defaultDurableState = collectDefaultDurableState(entities);
  const sourceNotes = [
    ...(repository?.agent?.risk_notes ?? []),
    'This README is generated from Agent Atlas metadata. Update `.agent-atlas/**` or the referenced canonical docs, then regenerate it.',
  ];
  const lines = [
    GENERATED_HEADER,
    '',
    `# ${title}`,
    '',
    summary,
    '',
    '## Start Here',
    '',
    ...renderReadmeList(
      readmeMetadata.start_here ?? buildDefaultStartHere(repository, commands, cliGroups, cliReference),
    ),
    ...(docsIndex ? [`- Documentation entrypoint: [${docsIndex.title}](${docsIndex.uri}).`] : []),
    '',
    '## Agent Atlas',
    '',
    '- Root generated view: `docs/agents/atlas.md`.',
    '- Resolve a file: `atlas resolve-path <path> --path .`.',
    '- Build task context: `atlas context-pack "<task>" --path . --budget 4000`.',
    '- Refresh generated surfaces: `atlas maintain fix --path .`.',
    '- Check generated surfaces: `atlas maintain check --path .`.',
  ];

  appendGeneratedOverviewSection(lines, readmeMetadata, workflows, components, cliGroups);
  appendNormalUseSection(lines, readmeMetadata, commands, cliGroups, tests);
  appendConfiguredSections(lines, readmeMetadata.sections);
  appendReadmeTextSection(lines, 'Current Truth Order', readmeMetadata.current_truth_order);
  appendReadmeLinkSection(lines, 'Key Docs', readmeMetadata.key_docs ?? defaultKeyDocs);
  appendReadmePathSection(lines, 'Durable State', readmeMetadata.durable_state ?? defaultDurableState);
  appendReadmeTextSection(lines, 'Operational Notes', readmeMetadata.operational_notes);
  appendCliSection(lines, readmeMetadata.cli, cliReference, cliGroups);
  appendReadmeSection(lines, 'Domains', domains);
  appendReadmeSection(lines, 'Key Implementation Surfaces', components);
  appendDrillDownSection(lines, documents);
  appendVerificationSection(lines, tests);

  if (commands.length > 0) {
    lines.push('', '## Commands', '');
    for (const command of commands) {
      lines.push(`- \`${command.command}\`${command.purpose ? ` - ${command.purpose}` : ''}`);
    }
  }

  lines.push('', '## Source Of Truth', '', ...sourceNotes.map((note) => `- ${note}`));
  return `${lines.join('\n')}\n`;
}

export function renderEntityCard(
  entity: AtlasEntity,
  edges: AtlasGraphEdge[] = [],
  profile: MarkdownProfile = 'public',
): string {
  const outgoing = edges.filter((edge) => edge.source === entity.id);
  const verification = outgoing.filter((edge) => edge.type === 'tested-by');
  const lines = [
    GENERATED_HEADER,
    '',
    `# ${entity.title}`,
    '',
    `ID: \`${entity.id}\``,
    `Kind: \`${entity.kind}\``,
    `Profile: \`${profile}\``,
    '',
    entity.summary,
  ];

  const metadata = renderMetadata(entity);
  if (metadata.length > 0) {
    lines.push('', '## Metadata', '', ...metadata);
  }

  const drillDown = renderLocalDrillDown(entity, edges);
  if (drillDown.length > 0) {
    lines.push('', '## Drill Down', '', ...drillDown);
  }

  if (entity.code?.paths?.length || entity.code?.entrypoints?.length) {
    lines.push('', '## Code', '');
    for (const codePath of entity.code.paths ?? []) {
      lines.push(`- path: \`${codePath}\``);
    }
    for (const entrypoint of entity.code.entrypoints ?? []) {
      lines.push(`- entrypoint: \`${entrypoint}\``);
    }
  }

  if (entity.uri || entity.access) {
    lines.push('', '## Access', '');
    if (entity.uri) {
      lines.push(`- uri: \`${renderUri(entity.uri, profile)}\``);
    }
    if (entity.access?.method) {
      lines.push(`- method: \`${entity.access.method}\``);
    }
    if (profile !== 'public' && entity.access?.server) {
      lines.push(`- server: \`${entity.access.server}\``);
    }
    if (profile !== 'public' && entity.access?.permission) {
      lines.push(`- permission: \`${entity.access.permission}\``);
    }
    if (entity.access?.private_overlay_required || isPrivateUri(entity.uri)) {
      lines.push('- private overlay required');
    }
  }

  lines.push('', '## Relations', '', renderRelationGroups(outgoing));

  if (verification.length > 0) {
    lines.push('', '## Verification', '');
    for (const edge of verification) {
      lines.push(`- \`${edge.target}\``);
    }
  }

  if (entity.agent) {
    lines.push('', '## Agent Hints', '');
    for (const hint of entity.agent.load_when ?? []) {
      lines.push(`- load when: ${hint}`);
    }
    for (const hint of entity.agent.avoid_loading_when ?? []) {
      lines.push(`- avoid when: ${hint}`);
    }
    if (entity.agent.token_budget_hint !== undefined) {
      lines.push(`- token budget hint: ${entity.agent.token_budget_hint}`);
    }
    for (const note of entity.agent.risk_notes ?? []) {
      lines.push(`- risk: ${note}`);
    }
  }

  return `${lines.join('\n')}\n`;
}

function renderRootAtlasView(
  entities: AtlasEntity[],
  edges: AtlasGraphEdge[],
  profile: MarkdownProfile,
): string {
  const graph: AtlasGraph = {
    rootPath: '.',
    entities,
    edges,
    index: createGraphIndex(entities, edges),
    diagnostics: [],
  };
  return `${GENERATED_HEADER}\n\n${renderAtlasOverviewMarkdown(createAtlasOverview(graph, profile))}`;
}

function renderVerificationView(
  entities: AtlasEntity[],
  edges: AtlasGraphEdge[],
  profile: MarkdownProfile,
): string {
  const tests = entities.filter((entity) => entity.kind === 'test-scope');
  const lines = [
    GENERATED_HEADER,
    '',
    '# Verification',
    '',
    `Profile: \`${profile}\``,
    '',
    '## Test Scopes',
    '',
    renderEntityList(tests),
  ];

  for (const test of tests) {
    lines.push('', `## ${test.title}`, '', `ID: \`${test.id}\``, '', test.summary);
    for (const command of test.commands ?? []) {
      lines.push('', `- command: \`${command.command}\``);
      if (command.purpose) {
        lines.push(`  purpose: ${command.purpose}`);
      }
    }

    const verifies = edges.filter((edge) => edge.source === test.id && edge.type === 'verifies');
    if (verifies.length > 0) {
      lines.push('', 'Verifies:');
      for (const edge of verifies) {
        lines.push(`- \`${edge.target}\``);
      }
    }
  }

  return `${lines.join('\n')}\n`;
}

function renderEntityDirectoryIndex(
  kind: AtlasEntityKind,
  entities: AtlasEntity[],
  profile: MarkdownProfile,
): string {
  const title = titleCase(`${kind} index`);
  const lines = [
    GENERATED_HEADER,
    '',
    `# ${title}`,
    '',
    `Profile: \`${profile}\``,
    '',
    `Generated index of visible \`${kind}\` entities.`,
    '',
  ];

  const cliInterfaces = kind === 'interface' ? entities.filter((entity) => isRecord(entity.metadata?.cli)) : [];
  if (cliInterfaces.length > 0) {
    lines.push('## CLI Command Groups', '');
    for (const group of groupCliInterfaceLinks(cliInterfaces)) {
    lines.push(`- ${group.title} (${group.items.length})${group.description ? `: ${group.description} ` : ': '}${group.items.map((item) => `[${item.label}](${item.path})`).join(', ')}`);
    }
    const otherInterfaces = entities.filter((entity) => !isRecord(entity.metadata?.cli));
    if (otherInterfaces.length > 0) {
      lines.push('', '## Other Interfaces', '', ...renderLinkedEntityList(otherInterfaces));
    }
  } else {
    lines.push(...renderLinkedEntityList(entities));
  }

  return `${lines.join('\n')}\n`;
}

function filterEntitiesByProfile(entities: AtlasEntity[], profile: MarkdownProfile): AtlasEntity[] {
  if (profile !== 'public') {
    return [...entities].sort(compareEntities);
  }

  return entities
    .filter((entity) => entity.visibility === undefined || entity.visibility === 'public')
    .sort(compareEntities);
}

function renderMetadata(entity: AtlasEntity): string[] {
  const metadata: string[] = [];
  if (entity.status) {
    metadata.push(`- status: \`${entity.status}\``);
  }
  if (entity.visibility) {
    metadata.push(`- visibility: \`${entity.visibility}\``);
  }
  if (entity.tags?.length) {
    metadata.push(`- tags: ${entity.tags.map((tag) => `\`${tag}\``).join(', ')}`);
  }
  if (entity.owners?.length) {
    metadata.push(`- owners: ${entity.owners.join(', ')}`);
  }
  return metadata;
}

function renderLocalDrillDown(entity: AtlasEntity, edges: AtlasGraphEdge[]): string[] {
  if (isPackageComponent(entity)) {
    return renderPackageDrillDown(entity, edges);
  }

  if (entity.kind !== 'domain' && entity.kind !== 'workflow') {
    return [];
  }

  const lines: string[] = [];
  const workflows = relatedEntities(entity.id, 'contains', 'workflow', edges);
  const capabilities = relatedEntities(entity.id, ['contains', 'uses', 'implements'], 'capability', edges);
  const components = relatedEntities(entity.id, ['contains', 'uses', 'implemented-by'], 'component', edges);
  const documents = relatedEntities(entity.id, 'documented-in', 'document', edges);
  const tests = relatedEntities(entity.id, 'tested-by', 'test-scope', edges);

  if (workflows.length > 0) {
    lines.push('### Workflows', '', ...workflows.map((id) => `- \`${id}\``), '');
  }
  if (capabilities.length > 0) {
    lines.push('### Capabilities', '', ...capabilities.map((id) => `- \`${id}\``), '');
  }
  if (components.length > 0) {
    lines.push('### Components', '', ...components.map((id) => `- \`${id}\``), '');
  }
  if (documents.length > 0) {
    lines.push('### Documents', '', ...documents.map((id) => `- \`${id}\``), '');
  }
  if (tests.length > 0) {
    lines.push('### Tests', '', ...tests.map((id) => `- \`${id}\``));
  }

  return lines.filter((line, index, all) => !(line === '' && all[index - 1] === ''));
}

function renderPackageDrillDown(entity: AtlasEntity, edges: AtlasGraphEdge[]): string[] {
  const lines: string[] = [];
  const metadata = readPackageMetadata(entity);
  const packageFacts = [
    metadata.root ? `root: \`${metadata.root}\`` : undefined,
    metadata.path ? `manifest: \`${metadata.path}\`` : undefined,
    metadata.exports?.length ? `exports: ${metadata.exports.map((item) => `\`${item}\``).join(', ')}` : undefined,
  ].filter((item): item is string => Boolean(item));

  if (packageFacts.length > 0) {
    lines.push('### Package Facts', '', ...packageFacts.map((item) => `- ${item}`), '');
  }
  if (metadata.scripts?.length) {
    lines.push('### Scripts', '', ...metadata.scripts.map((script) => `- \`${script}\``), '');
  }
  appendPackageDrillDownGroup(lines, 'Interfaces', relatedEntities(entity.id, 'contains', 'interface', edges));
  appendPackageDrillDownGroup(lines, 'Components', relatedEntities(entity.id, 'contains', 'component', edges));
  appendPackageDrillDownGroup(lines, 'Documents', relatedEntities(entity.id, 'contains', 'document', edges));
  appendPackageDrillDownGroup(lines, 'Config', relatedEntities(entity.id, 'contains', 'resource', edges));
  appendPackageDrillDownGroup(lines, 'Tests', relatedEntities(entity.id, 'contains', 'test-scope', edges));
  return lines.filter((line, index, all) => !(line === '' && all[index - 1] === ''));
}

function appendPackageDrillDownGroup(lines: string[], title: string, ids: AtlasEntityId[]): void {
  if (ids.length === 0) {
    return;
  }
  lines.push(`### ${title}`, '', ...ids.map((id) => `- \`${id}\``), '');
}

function relatedEntities(
  sourceId: AtlasEntityId,
  relationType: string | string[],
  targetKind: AtlasEntityKind,
  edges: AtlasGraphEdge[],
): AtlasEntityId[] {
  const relationTypes = Array.isArray(relationType) ? relationType : [relationType];
  return [
    ...new Set(
      edges
        .filter(
          (edge) =>
            edge.source === sourceId &&
            relationTypes.includes(edge.type) &&
            edge.target.startsWith(`${targetKind}:`),
        )
        .map((edge) => edge.target),
    ),
  ].sort();
}

function renderUri(uri: string, profile: MarkdownProfile): string {
  if (profile === 'public' && isPrivateUri(uri)) {
    return '[redacted: private reference]';
  }

  return uri;
}

function collectReadmeEntities(
  repositoryId: AtlasEntityId | undefined,
  kind: AtlasEntityKind,
  entities: AtlasEntity[],
  edges: AtlasGraphEdge[],
): AtlasEntity[] {
  const candidates = entities.filter((entity) => entity.kind === kind);
  if (!repositoryId) {
    return candidates.sort(compareEntities);
  }

  const relatedIds = new Set(
    edges
      .filter((edge) => edge.source === repositoryId || edge.target === repositoryId)
      .flatMap((edge) => [edge.source, edge.target])
      .filter((id) => id !== repositoryId),
  );
  const directlyRelated = candidates.filter((entity) => relatedIds.has(entity.id));
  return (directlyRelated.length > 0 ? directlyRelated : candidates).sort(compareEntities);
}

function appendReadmeSection(lines: string[], title: string, entities: AtlasEntity[]): void {
  if (entities.length === 0) {
    return;
  }

  lines.push('', `## ${title}`, '');
  for (const entity of entities) {
    const target = entity.uri && !isPrivateUri(entity.uri) ? ` ([source](${entity.uri}))` : '';
    lines.push(`- \`${entity.id}\` - ${entity.title}: ${entity.summary}${target}`);
  }
}

function appendDrillDownSection(lines: string[], documents: AtlasEntity[]): void {
  lines.push('', '## Drill Down', '');
  lines.push('- Atlas overview: `docs/agents/atlas.md`.');
  lines.push('- Entity indexes: `docs/agents/domains/`, `docs/agents/workflows/`, `docs/agents/components/`, and `docs/agents/capabilities/`.');
  lines.push('- Source-derived inventory: `docs/generated/source-derived-reference.md`.');
  const docsIndex = documents.find((document) => document.uri === 'docs/index.md');
  if (docsIndex?.uri) {
    lines.push(`- Documentation map: [${docsIndex.title}](${docsIndex.uri}).`);
  } else {
    lines.push('- Documentation map: `docs/index.md` when present.');
  }
}

function appendVerificationSection(lines: string[], tests: AtlasEntity[]): void {
  lines.push('', '## Verification', '');
  const commands = collectTestCommands(tests).slice(0, 8);
  if (commands.length > 0) {
    for (const command of commands) {
      lines.push(`- \`${command.command}\`${command.purpose ? ` - ${command.purpose}` : ''}`);
    }
  } else {
    lines.push('- Use the repo-local test and check scripts advertised by package metadata.');
  }
  lines.push('- Scoped verification map: `docs/agents/verification.md`.');
  lines.push('- Task-specific verification: `atlas context-pack "<task>" --path . --budget 4000`.');
}

function collectTestCommands(tests: AtlasEntity[]): NonNullable<AtlasEntity['commands']> {
  const seen = new Set<string>();
  const commands: NonNullable<AtlasEntity['commands']> = [];
  for (const command of tests.flatMap((test) => test.commands ?? [])) {
    if (seen.has(command.command)) {
      continue;
    }
    seen.add(command.command);
    commands.push(command);
  }
  return commands;
}

function isAgentSkillDocument(entity: AtlasEntity): boolean {
  return Boolean(entity.uri && /^\.agents\/skills\/[^/]+\/SKILL\.md$/i.test(entity.uri));
}

function collectReadmeCommands(
  repository: AtlasEntity | undefined,
  tests: AtlasEntity[],
): NonNullable<AtlasEntity['commands']> {
  const seen = new Set<string>();
  const commands: NonNullable<AtlasEntity['commands']> = [];
  for (const command of [...(repository?.commands ?? []), ...tests.flatMap((test) => test.commands ?? [])]) {
    if (seen.has(command.command)) {
      continue;
    }
    seen.add(command.command);
    commands.push(command);
  }
  return commands.slice(0, 10);
}

function collectReadmeCliInterfaces(
  repositoryId: AtlasEntityId | undefined,
  entities: AtlasEntity[],
  edges: AtlasGraphEdge[],
): AtlasEntity[] {
  const cliInterfaces = entities.filter((entity) => entity.kind === 'interface' && isRecord(entity.metadata?.cli));
  if (!repositoryId || cliInterfaces.length === 0) {
    return cliInterfaces.sort(compareCliInterfaces);
  }

  const relatedIds = new Set(
    edges
      .filter((edge) => edge.source === repositoryId || edge.target === repositoryId)
      .flatMap((edge) => [edge.source, edge.target])
      .filter((id) => id !== repositoryId),
  );
  const directlyRelated = cliInterfaces.filter((entity) => relatedIds.has(entity.id));
  return (directlyRelated.length > 0 ? directlyRelated : cliInterfaces).sort(compareCliInterfaces);
}

function buildDefaultStartHere(
  repository: AtlasEntity | undefined,
  commands: NonNullable<AtlasEntity['commands']>,
  cliGroups: CliInterfaceGroup[],
  cliReference: ReadmeLinkItem | undefined,
): string[] {
  const lines: string[] = [];
  lines.push(`Use this repo for ${summaryFragment(repository?.summary ?? 'the capabilities described below')}.`);
  const sessionStart = findSessionStartCommand(commands, cliGroups);
  if (sessionStart) {
    lines.push(`Start normal sessions with \`${sessionStart.command}\`, then use Atlas before broad repository search.`);
  } else {
    lines.push('Use Agent Atlas before broad repository search, then load only task-relevant entities or docs.');
  }
  if (cliGroups.length > 0) {
    lines.push(
      `Use the CLI overview below for ${cliGroups.length} command ${cliGroups.length === 1 ? 'group' : 'groups'}${cliReference ? `, with exact syntax in [${cliReference.label}](${cliReference.path})` : ''}.`,
    );
  }
  lines.push('If generated README or Atlas output is missing or misleading, update `.agent-atlas/**` or the referenced canonical docs, then regenerate.');
  return lines;
}

function appendGeneratedOverviewSection(
  lines: string[],
  readmeMetadata: RepositoryReadmeMetadata,
  workflows: AtlasEntity[],
  components: AtlasEntity[],
  cliGroups: CliInterfaceGroup[],
): void {
  const hasConfiguredOverview = readmeMetadata.sections?.some((section) => section.title.toLowerCase() === 'what this repo does');
  if (hasConfiguredOverview) {
    return;
  }
  const items = [
    ...workflows.slice(0, 6).map((workflow) => `${workflow.title}: ${workflow.summary}`),
    ...components.slice(0, Math.max(0, 6 - workflows.length)).map((component) => `${component.title}: ${component.summary}`),
  ];
  if (items.length === 0 && cliGroups.length > 0) {
    items.push(...cliGroups.slice(0, 6).map((group) => `${group.title}: ${group.description ?? 'Command group exposed by the generated CLI catalog.'}`));
  }
  appendReadmeTextSection(lines, 'What This Repo Does', items);
}

function appendNormalUseSection(
  lines: string[],
  readmeMetadata: RepositoryReadmeMetadata,
  commands: NonNullable<AtlasEntity['commands']>,
  cliGroups: CliInterfaceGroup[],
  tests: AtlasEntity[],
): void {
  const configuredNormalUse = readmeMetadata.sections?.some((section) => section.title.toLowerCase() === 'normal use');
  if (configuredNormalUse) {
    return;
  }
  const items: string[] = [];
  const sessionStart = findSessionStartCommand(commands, cliGroups);
  if (sessionStart) {
    items.push(`Start with \`${sessionStart.command}\`${sessionStart.purpose ? ` to ${lowercaseFirst(sessionStart.purpose)}` : ' for repo orientation'}.`);
  }
  if (cliGroups.length > 0) {
    items.push('Use the main CLI command groups below to find the repo-supported workflows and exact entrypoints.');
  }
  items.push('Use `atlas context-pack "<task>" --path . --budget 4000` or `atlas resolve-path <path> --path .` to choose task-specific reads before broad search.');
  const verificationCommand =
    commands.find((command) => /\bverify:session\b/.test(command.command)) ??
    commands.find((command) => /verify/i.test(command.command)) ??
    collectTestCommands(tests)[0] ??
    commands.find((command) => /test|check/i.test(command.command));
  if (verificationCommand) {
    items.push(`Verify meaningful changes with \`${verificationCommand.command}\`${verificationCommand.purpose ? ` to ${lowercaseFirst(verificationCommand.purpose)}` : ''}.`);
  }
  appendReadmeTextSection(lines, 'Normal Use', items);
}

function collectDefaultKeyDocs(documents: AtlasEntity[], cliReference: ReadmeLinkItem | undefined): ReadmeLinkItem[] | undefined {
  const candidates = [
    findDocumentLink(documents, 'AGENTS.md', 'Repo-local operating instructions and agent guidance.'),
    findDocumentLink(documents, 'docs/index.md', 'Documentation map and deeper docs entrypoint.'),
    findDocumentByPathPattern(documents, /coding-standard/i, 'Default coding or contribution standard.'),
    cliReference,
    findDocumentByPathPattern(documents, /docs\/(vision|principles|non-goals|architecture|concepts)\b/i, 'Project direction, architecture, or scope context.'),
  ].filter((item): item is ReadmeLinkItem => Boolean(item));
  const deduped = dedupeLinkItems(candidates);
  return deduped.length > 0 ? deduped : undefined;
}

function findSessionStartCommand(
  commands: NonNullable<AtlasEntity['commands']>,
  cliGroups: CliInterfaceGroup[],
): { command: string; purpose?: string } | undefined {
  const repositoryCommand = commands.find((command) => /session:start\b/.test(command.command));
  if (repositoryCommand) {
    return repositoryCommand;
  }
  const cliCommand = cliGroups.flatMap((group) => group.commands).find((command) => /session:start\b/.test(command));
  return cliCommand ? { command: cliCommand } : undefined;
}

function collectDefaultDurableState(entities: AtlasEntity[]): ReadmePathItem[] | undefined {
  const paths = new Map<string, string>();
  for (const entity of entities) {
    for (const pathValue of collectEntityPaths(entity)) {
      const root = durableRootForPath(pathValue);
      if (root) {
        paths.set(root.path, paths.get(root.path) ?? root.note ?? '');
      }
    }
  }
  const preferredOrder = ['.agent-atlas/', 'docs/agents/', 'docs/generated/', 'registry/', '.agents/skills/', 'evals/', '.runtime/', 'packages/'];
  const items = [...paths.entries()].map(([pathValue, note]) => ({ path: pathValue, note }));
  items.sort((left, right) => preferredIndex(preferredOrder, left.path) - preferredIndex(preferredOrder, right.path) || left.path.localeCompare(right.path));
  return items.slice(0, 8).length > 0 ? items.slice(0, 8) : undefined;
}

function collectEntityPaths(entity: AtlasEntity): string[] {
  return [entity.uri, ...(entity.code?.paths ?? []), ...(entity.code?.entrypoints ?? [])].filter((pathValue): pathValue is string => Boolean(pathValue));
}

function durableRootForPath(pathValue: string): ReadmePathItem | undefined {
  const normalized = pathValue.replaceAll('\\', '/');
  const root = normalized.split('/')[0];
  if (normalized.startsWith('.agent-atlas/')) return { path: '.agent-atlas/', note: 'Canonical Atlas metadata and overlays.' };
  if (normalized.startsWith('docs/agents/')) return { path: 'docs/agents/', note: 'Generated Atlas Markdown views.' };
  if (normalized.startsWith('docs/generated/')) return { path: 'docs/generated/', note: 'Generated references and inventories.' };
  if (normalized.startsWith('registry/')) return { path: 'registry/', note: 'Registry and tracked operational definitions.' };
  if (normalized.startsWith('.agents/skills/')) return { path: '.agents/skills/', note: 'Reusable agent workflows.' };
  if (normalized.startsWith('evals/')) return { path: 'evals/', note: 'Workflow protections and regression checks.' };
  if (normalized.startsWith('.runtime/')) return { path: '.runtime/', note: 'Generated runtime and current-state artifacts.' };
  if (normalized.startsWith('packages/')) return { path: 'packages/', note: 'Workspace packages and implementation surfaces.' };
  if (['docs', 'examples', 'apps', 'scripts'].includes(root)) return { path: `${root}/`, note: titleCase(`${root} surfaces.`) };
  return undefined;
}

function findDocumentLink(documents: AtlasEntity[], pathValue: string, note: string): ReadmeLinkItem | undefined {
  const document = documents.find((entity) => entity.uri === pathValue);
  return document?.uri ? { label: document.title, path: document.uri, note } : undefined;
}

function findDocumentByPathPattern(documents: AtlasEntity[], pattern: RegExp, note: string): ReadmeLinkItem | undefined {
  const document = documents.find((entity) => Boolean(entity.uri && pattern.test(entity.uri)));
  return document?.uri && !isPrivateUri(document.uri) ? { label: document.title, path: document.uri, note } : undefined;
}

function dedupeLinkItems(items: ReadmeLinkItem[]): ReadmeLinkItem[] {
  const seen = new Set<string>();
  return items.filter((item) => {
    if (seen.has(item.path)) return false;
    seen.add(item.path);
    return true;
  });
}

function preferredIndex(order: string[], value: string): number {
  const index = order.indexOf(value);
  return index === -1 ? Number.MAX_SAFE_INTEGER : index;
}

function lowercaseFirst(value: string): string {
  return value.length > 0 ? `${value.charAt(0).toLowerCase()}${value.slice(1).replace(/\.$/, '')}` : value;
}

function summaryFragment(value: string): string {
  return lowercaseFirst(value.trim());
}

function readRepositoryReadmeMetadata(repository: AtlasEntity | undefined): RepositoryReadmeMetadata {
  const metadata = isRecord(repository?.metadata) ? repository?.metadata : undefined;
  const readme = isRecord(metadata?.readme) ? metadata?.readme : undefined;
  return {
    start_here: readStringArray(readme?.start_here),
    current_truth_order: readStringArray(readme?.current_truth_order),
    key_docs: readLinkItems(readme?.key_docs),
    durable_state: readPathItems(readme?.durable_state),
    operational_notes: readStringArray(readme?.operational_notes),
    sections: readSections(readme?.sections),
    cli: readCliMetadata(readme?.cli),
  };
}

function appendReadmeTextSection(lines: string[], title: string, items: string[] | undefined): void {
  if (!items?.length) {
    return;
  }
  lines.push('', `## ${title}`, '', ...renderReadmeList(items));
}

function appendReadmeLinkSection(lines: string[], title: string, items: ReadmeLinkItem[] | undefined): void {
  if (!items?.length) {
    return;
  }
  lines.push('', `## ${title}`, '');
  for (const item of items) {
    lines.push(`- [${item.label}](${item.path})${item.note ? ` - ${item.note}` : ''}`);
  }
}

function appendReadmePathSection(lines: string[], title: string, items: ReadmePathItem[] | undefined): void {
  if (!items?.length) {
    return;
  }
  lines.push('', `## ${title}`, '');
  for (const item of items) {
    lines.push(`- \`${item.path}\`${item.note ? ` - ${item.note}` : ''}`);
  }
}

function appendConfiguredSections(lines: string[], sections: ReadmeSection[] | undefined): void {
  for (const section of sections ?? []) {
    appendReadmeTextSection(lines, section.title, section.items);
  }
}

function appendCliSection(
  lines: string[],
  cliMetadata: ReadmeCliMetadata | undefined,
  reference: ReadmeLinkItem | undefined,
  interfaceGroups: CliInterfaceGroup[],
): void {
  if (!cliMetadata?.overview?.length && !reference && interfaceGroups.length === 0) {
    return;
  }

  lines.push('', '## CLI', '');
  if (cliMetadata?.overview?.length) {
    lines.push(...renderReadmeList(cliMetadata.overview), '');
  }
  if (reference) {
    lines.push(`- Full command reference: [${reference.label}](${reference.path})${reference.note ? ` - ${reference.note}` : ''}`);
  }

  if (interfaceGroups.length > 0) {
    lines.push('', '### Command Groups', '', '| Group | Purpose | Example |', '| --- | --- | --- |');
  }
  for (const group of interfaceGroups) {
    const shownCommands = group.commands.slice(0, README_CLI_GROUP_COMMAND_LIMIT);
    const hiddenCount = group.commands.length - shownCommands.length;
    const groupLabel = reference
      ? `[${group.title}](${reference.path}#${githubHeadingAnchor(group.title)})`
      : group.title;
    const commandSummary = [
      ...shownCommands.map((command) => `\`${command}\``),
      ...(hiddenCount > 0 ? [`+${hiddenCount} more`] : []),
    ].join(' ');
    lines.push(
      `| ${groupLabel} (${group.commands.length}) | ${escapeMarkdownTableCell(group.description ?? 'See the command reference for details.')} | ${commandSummary} |`,
    );
  }
}

function githubHeadingAnchor(title: string): string {
  return title
    .trim()
    .toLowerCase()
    .replace(/`/g, '')
    .replace(/&/g, 'and')
    .replace(/[^a-z0-9 -]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-');
}

function escapeMarkdownTableCell(value: string): string {
  return value.replace(/\|/g, '\\|').replace(/\r?\n/g, ' ');
}

function renderReadmeList(items: string[]): string[] {
  return items.map((item) => `- ${item}`);
}

function readStringArray(value: unknown): string[] | undefined {
  if (!Array.isArray(value)) {
    return undefined;
  }
  const strings = value.filter((item): item is string => typeof item === 'string' && item.trim().length > 0);
  return strings.length > 0 ? strings : undefined;
}

function readLinkItems(value: unknown): ReadmeLinkItem[] | undefined {
  if (!Array.isArray(value)) {
    return undefined;
  }
  const items: ReadmeLinkItem[] = [];
  for (const item of value) {
    if (!isRecord(item)) {
      continue;
    }
    const label = readString(item.label);
    const pathValue = readString(item.path);
    if (!label || !pathValue) {
      continue;
    }
    const note = readString(item.note);
    items.push(note ? { label, path: pathValue, note } : { label, path: pathValue });
  }
  return items.length > 0 ? items : undefined;
}

function readPathItems(value: unknown): ReadmePathItem[] | undefined {
  if (!Array.isArray(value)) {
    return undefined;
  }
  const items: ReadmePathItem[] = [];
  for (const item of value) {
    if (!isRecord(item)) {
      continue;
    }
    const pathValue = readString(item.path);
    if (!pathValue) {
      continue;
    }
    const note = readString(item.note);
    items.push(note ? { path: pathValue, note } : { path: pathValue });
  }
  return items.length > 0 ? items : undefined;
}

function readSections(value: unknown): ReadmeSection[] | undefined {
  if (!Array.isArray(value)) {
    return undefined;
  }
  const sections = value
    .filter(isRecord)
    .map((item) => ({
      title: readString(item.title),
      items: readStringArray(item.items),
    }))
    .filter((item): item is ReadmeSection => Boolean(item.title && item.items?.length));
  return sections.length > 0 ? sections : undefined;
}

function readCliMetadata(value: unknown): ReadmeCliMetadata | undefined {
  if (!isRecord(value)) {
    return undefined;
  }
  const cli: ReadmeCliMetadata = {
    overview: readStringArray(value.overview),
    reference: readLinkItems(value.reference ? [value.reference] : undefined)?.[0],
  };
  return cli.overview?.length || cli.reference ? cli : undefined;
}

function findCliReference(documents: AtlasEntity[]): ReadmeLinkItem | undefined {
  const document = documents.find(
    (entity) =>
      entity.id.includes('cli-command-reference') ||
      entity.uri === 'docs/generated/cli-command-reference.md' ||
      entity.title.toLowerCase().includes('cli command reference'),
  );
  if (!document?.uri || isPrivateUri(document.uri)) {
    return undefined;
  }
  return {
    label: document.title,
    path: document.uri,
    note: document.summary,
  };
}

function groupCliInterfaces(interfaces: AtlasEntity[]): CliInterfaceGroup[] {
  const groups = new Map<string, { description?: string; commands: string[] }>();
  for (const entity of interfaces) {
    const cli = isRecord(entity.metadata?.cli) ? entity.metadata.cli : undefined;
    const cliName = readString(cli?.cli_name);
    const command = readString(cli?.command);
    const label = [cliName, command].filter(Boolean).join(' ') || entity.title;
    const group = normalizeCliGroupTitle(readString(cli?.group) ?? 'CLI Commands');
    const current = groups.get(group) ?? { commands: [] };
    current.description = current.description ?? readString(cli?.group_description) ?? readString(cli?.group_summary);
    current.commands.push(label);
    groups.set(group, current);
  }

  return [...groups.entries()]
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([title, group]) => ({
      title,
      description: group.description,
      commands: [...new Set(group.commands)].sort((left, right) => left.localeCompare(right)),
    }));
}

function groupCliInterfaceLinks(
  interfaces: AtlasEntity[],
): Array<{ title: string; description?: string; items: Array<{ label: string; path: string }> }> {
  const groups = new Map<string, { description?: string; items: Array<{ label: string; path: string }> }>();
  for (const entity of interfaces) {
    const cli = isRecord(entity.metadata?.cli) ? entity.metadata.cli : undefined;
    const cliName = readString(cli?.cli_name);
    const command = readString(cli?.command);
    const label = [cliName, command].filter(Boolean).join(' ') || entity.title;
    const group = normalizeCliGroupTitle(readString(cli?.group) ?? 'CLI Commands');
    const current = groups.get(group) ?? { items: [] };
    current.description = current.description ?? readString(cli?.group_description) ?? readString(cli?.group_summary);
    current.items.push({ label, path: `${entitySlug(entity.id)}.md` });
    groups.set(group, current);
  }

  return [...groups.entries()]
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([title, group]) => ({
      title,
      description: group.description,
      items: group.items.sort((left, right) => left.label.localeCompare(right.label)),
    }));
}

function normalizeCliGroupTitle(group: string): string {
  return group.replace(/:+$/g, '').trim() || 'CLI Commands';
}

function compareCliInterfaces(left: AtlasEntity, right: AtlasEntity): number {
  const leftCli = isRecord(left.metadata?.cli) ? left.metadata.cli : undefined;
  const rightCli = isRecord(right.metadata?.cli) ? right.metadata.cli : undefined;
  const leftGroup = readString(leftCli?.group) ?? '';
  const rightGroup = readString(rightCli?.group) ?? '';
  const groupCompare = leftGroup.localeCompare(rightGroup);
  if (groupCompare !== 0) return groupCompare;
  return left.id.localeCompare(right.id);
}

function readString(value: unknown): string | undefined {
  return typeof value === 'string' && value.trim().length > 0 ? value : undefined;
}

function readStringList(value: unknown): string[] | undefined {
  if (!Array.isArray(value)) {
    return undefined;
  }
  const strings = value.filter((item): item is string => typeof item === 'string' && item.trim().length > 0);
  return strings.length > 0 ? strings : undefined;
}

function isPackageComponent(entity: AtlasEntity): boolean {
  return entity.kind === 'component' && isRecord(entity.metadata?.package);
}

function readPackageMetadata(entity: AtlasEntity): {
  path?: string;
  root?: string;
  scripts?: string[];
  exports?: string[];
} {
  const packageMetadata = isRecord(entity.metadata?.package) ? entity.metadata.package : {};
  return {
    path: readString(packageMetadata.path),
    root: readString(packageMetadata.root),
    scripts: readStringList(packageMetadata.scripts),
    exports: readStringList(packageMetadata.exports),
  };
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function isPrivateUri(uri: string | undefined): boolean {
  if (!uri) {
    return false;
  }

  const lowerUri = uri.toLowerCase();
  return (
    ['notion:', 'confluence:', 'jira:', 'gdrive:', 'google-drive:', 'gcal:', 'slack:', 'mailto:'].some(
      (scheme) => lowerUri.startsWith(scheme),
    ) ||
    lowerUri.includes('localhost') ||
    /^https?:\/\/(10\.|127\.|192\.168\.|172\.(1[6-9]|2\d|3[0-1])\.)/.test(lowerUri)
  );
}

function renderRelationGroups(edges: AtlasGraphEdge[]): string {
  if (edges.length === 0) {
    return '- No relations declared.';
  }

  const grouped = new Map<string, AtlasGraphEdge[]>();
  for (const edge of edges) {
    const group = grouped.get(edge.type) ?? [];
    group.push(edge);
    grouped.set(edge.type, group);
  }

  return [...grouped.entries()]
    .sort(([left], [right]) => left.localeCompare(right))
    .flatMap(([type, group]) => [
      `### \`${type}\``,
      '',
      ...group.map((edge) => `- \`${edge.target}\`${edge.provenance === 'generated' ? ' _(generated)_' : ''}`),
      '',
    ])
    .join('\n')
    .trimEnd();
}

function renderEntityList(entities: AtlasEntity[]): string {
  if (entities.length === 0) {
    return '- None.';
  }

  return entities
    .sort(compareEntities)
    .map((entity) => `- \`${entity.id}\` - ${entity.title}: ${entity.summary}`)
    .join('\n');
}

function renderLinkedEntityList(entities: AtlasEntity[]): string[] {
  if (entities.length === 0) {
    return ['- None.'];
  }

  return entities
    .sort(compareEntities)
    .map((entity) => `- [${entity.title}](${entitySlug(entity.id)}.md) - \`${entity.id}\`: ${entity.summary}`);
}

function entitySlug(id: AtlasEntityId): string {
  return id.slice(id.indexOf(':') + 1).replaceAll('/', '__');
}

function compareEntities(left: AtlasEntity, right: AtlasEntity): number {
  const kindCompare = left.kind.localeCompare(right.kind);
  if (kindCompare !== 0) return kindCompare;
  return left.id.localeCompare(right.id);
}

function titleCase(value: string): string {
  return value.replace(/\b[a-z]/g, (letter) => letter.toUpperCase());
}
