import path from 'node:path';
import { describe, expect, it } from 'vitest';
import { loadAtlasGraph } from '@agent-atlas/core';
import { generateMarkdownViews, renderEntityCard } from './index.js';

describe('generateMarkdownViews', () => {
  it('generates compact public markdown views', async () => {
    const graph = await loadAtlasGraph(path.resolve('../../examples/personal-ops-sanitized'));
    const files = generateMarkdownViews(graph, { profile: 'public' });
    const filePaths = files.map((file) => file.path);

    expect(filePaths).toContain('atlas.md');
    expect(filePaths).toContain('verification.md');
    expect(filePaths).toContain('domains/calendar.md');
    expect(filePaths).toContain('workflows/plan-week.md');
    expect(filePaths).toContain('components/weekly-planner.md');
    expect(filePaths).not.toContain('documents/weekly-planning-system.md');
    expect(files[0]?.content).toContain('<!-- Generated by Agent Atlas. Do not edit directly. -->');
  });

  it('includes private-profile files when requested', async () => {
    const graph = await loadAtlasGraph(path.resolve('../../examples/personal-ops-sanitized'), {
      profile: 'private',
    });
    const files = generateMarkdownViews(graph, { profile: 'private' });

    expect(files.map((file) => file.path)).toContain('documents/weekly-planning-system.md');
    expect(files.find((file) => file.path === 'documents/weekly-planning-system.md')?.content).toContain(
      'notion://page/sanitized-weekly-planning',
    );
  });

  it('redacts private references from public markdown cards', () => {
    const markdown = renderEntityCard(
      {
        id: 'document:release-process',
        kind: 'document',
        title: 'Release Process',
        summary: 'Internal release process.',
        visibility: 'public',
        uri: 'notion://page/sanitized-release-process',
      },
      [],
      'public',
    );

    expect(markdown).toContain('[redacted: private reference]');
    expect(markdown).not.toContain('notion://page/sanitized-release-process');
  });
});
