import path from 'node:path';
import { describe, expect, it } from 'vitest';
import { loadAtlasGraph } from '@agent-atlas/core';
import { generateMarkdownViews, renderEntityCard, renderRepositoryReadme } from './index.js';

describe('generateMarkdownViews', () => {
  it('generates compact public markdown views', async () => {
    const graph = await loadAtlasGraph(path.resolve('../../examples/personal-ops-sanitized'));
    const files = generateMarkdownViews(graph, { profile: 'public' });
    const filePaths = files.map((file) => file.path);

    expect(filePaths).toContain('atlas.md');
    expect(filePaths).toContain('verification.md');
    expect(filePaths).toContain('components/index.md');
    expect(filePaths).toContain('domains/calendar.md');
    expect(filePaths).toContain('domains/index.md');
    expect(filePaths).toContain('workflows/plan-week.md');
    expect(filePaths).toContain('workflows/index.md');
    expect(filePaths).toContain('components/weekly-planner.md');
    expect(filePaths).not.toContain('documents/weekly-planning-system.md');
    const root = files.find((file) => file.path === 'atlas.md')?.content ?? '';
    expect(root).toContain('<!-- Generated by Agent Atlas. Do not edit directly. -->');
    expect(root).toContain('# Atlas overview');
    expect(root).toContain('## Start here');
    const domainIndex = files.find((file) => file.path === 'domains/index.md')?.content ?? '';
    expect(domainIndex).toContain('# Domain Index');
    expect(domainIndex).toContain('[Calendar](calendar.md)');
  });

  it('includes private-profile files when requested', async () => {
    const graph = await loadAtlasGraph(path.resolve('../../examples/personal-ops-sanitized'), {
      profile: 'private',
    });
    const files = generateMarkdownViews(graph, { profile: 'private' });

    expect(files.map((file) => file.path)).toContain('documents/weekly-planning-system.md');
    expect(files.find((file) => file.path === 'documents/weekly-planning-system.md')?.content).toContain(
      'notion://page/sanitized-weekly-planning',
    );
  });

  it('redacts private references from public markdown cards', () => {
    const markdown = renderEntityCard(
      {
        id: 'document:release-process',
        kind: 'document',
        title: 'Release Process',
        summary: 'Internal release process.',
        visibility: 'public',
        uri: 'notion://page/sanitized-release-process',
      },
      [],
      'public',
    );

    expect(markdown).toContain('[redacted: private reference]');
    expect(markdown).not.toContain('notion://page/sanitized-release-process');
  });

  it('renders package component cards as package entrypoints', () => {
    const markdown = renderEntityCard(
      {
        id: 'component:package.example-core',
        kind: 'component',
        title: '@example/core',
        summary: 'Core package.',
        visibility: 'public',
        metadata: {
          package: {
            root: 'packages/core',
            path: 'packages/core/package.json',
            scripts: ['build'],
            exports: ['.', './cli'],
          },
        },
      },
      [
        {
          source: 'component:package.example-core',
          target: 'interface:package-script.example-core.build',
          type: 'contains',
          provenance: 'generated',
        },
        {
          source: 'component:package.example-core',
          target: 'test-scope:generated.package.example-core',
          type: 'contains',
          provenance: 'generated',
        },
      ],
      'public',
    );

    expect(markdown).toContain('## Drill Down');
    expect(markdown).toContain('### Package Facts');
    expect(markdown).toContain('- root: `packages/core`');
    expect(markdown).toContain('### Interfaces');
    expect(markdown).toContain('`interface:package-script.example-core.build`');
    expect(markdown).toContain('### Tests');
  });

  it('renders a compact repository README from visible atlas entities', () => {
    const markdown = renderRepositoryReadme(
      {
        rootPath: '.',
        index: {
          entitiesById: new Map(),
          outgoingById: new Map(),
          incomingById: new Map(),
        },
        diagnostics: [],
        entities: [
          {
            id: 'repository:example',
            kind: 'repository',
            title: 'example',
            summary: 'Example repository.',
            visibility: 'public',
            commands: [{ command: 'pnpm test', purpose: 'Run tests.' }],
            metadata: {
              readme: {
                start_here: ['Run `pnpm start`.', 'Read `AGENTS.md`.'],
                current_truth_order: ['Live refresh.', 'Generated current state.'],
                key_docs: [{ label: 'Agent Rules', path: 'AGENTS.md', note: 'Agent guidance.' }],
                durable_state: [{ path: 'registry/', note: 'Registry data.' }],
                operational_notes: ['Long-running launches need long timeouts.'],
                cli: {
                  overview: ['Use `example` for repository automation.'],
                  reference: {
                    label: 'CLI Reference',
                    path: 'docs/generated/cli-command-reference.md',
                    note: 'Generated command details.',
                  },
                },
                sections: [{ title: 'Custom Section', items: ['Custom item.'] }],
              },
            },
            relations: [
              { type: 'contains', target: 'workflow:ship' },
              { type: 'contains', target: 'document:docs-index' },
            ],
          },
          {
            id: 'workflow:ship',
            kind: 'workflow',
            title: 'Ship',
            summary: 'Release the package.',
            visibility: 'public',
          },
          {
            id: 'domain:example-domain',
            kind: 'domain',
            title: 'Example Domain',
            summary: 'Top-level domain context.',
            visibility: 'public',
          },
          {
            id: 'document:docs-index',
            kind: 'document',
            title: 'Docs Index',
            summary: 'Documentation entrypoint.',
            visibility: 'public',
            uri: 'docs/index.md',
          },
          {
            id: 'capability:agent-skill.ship',
            kind: 'capability',
            title: 'Ship skill',
            summary: 'Use when releasing the package.',
            visibility: 'public',
            uri: '.agents/skills/ship/SKILL.md',
          },
          {
            id: 'component:package.example-core',
            kind: 'component',
            title: '@example/core',
            summary: 'Core package.',
            visibility: 'public',
            uri: 'packages/core/package.json',
            metadata: {
              package: {
                name: '@example/core',
                root: 'packages/core',
                path: 'packages/core/package.json',
                scripts: ['build', 'test'],
                exports: ['.', './cli'],
              },
            },
          },
          {
            id: 'document:generated.agents-skills-ship-skill',
            kind: 'document',
            title: 'Ship skill',
            summary: 'Markdown document at .agents/skills/ship/SKILL.md.',
            visibility: 'public',
            uri: '.agents/skills/ship/SKILL.md',
          },
          {
            id: 'interface:example-cli.validate',
            kind: 'interface',
            title: 'example validate',
            summary: 'Validate repository metadata.',
            visibility: 'public',
            metadata: {
              cli: {
                cli_name: 'example',
                command: 'validate',
                usage: 'example validate [--json]',
                group: 'Validation Commands',
                group_description: 'Commands for validating repository metadata and generated artifacts.',
              },
            },
          },
          {
            id: 'document:private-runbook',
            kind: 'document',
            title: 'Private Runbook',
            summary: 'Private operational runbook.',
            visibility: 'private',
            uri: 'notion://page/private',
          },
        ],
        edges: [
          { source: 'repository:example', target: 'domain:example-domain', type: 'contains', provenance: 'explicit' },
          { source: 'repository:example', target: 'workflow:ship', type: 'contains', provenance: 'explicit' },
          { source: 'repository:example', target: 'capability:agent-skill.ship', type: 'contains', provenance: 'explicit' },
          { source: 'repository:example', target: 'document:docs-index', type: 'contains', provenance: 'explicit' },
          { source: 'repository:example', target: 'component:package.example-core', type: 'contains', provenance: 'generated' },
        ],
      },
      { profile: 'public' },
    );

    expect(markdown).toContain('<!-- Generated by Agent Atlas. Do not edit directly. -->');
    expect(markdown).toContain('# example');
    expect(markdown).toContain('- Run `pnpm start`.');
    expect(markdown).toContain('## Current Truth Order');
    expect(markdown).toContain('- [Agent Rules](AGENTS.md) - Agent guidance.');
    expect(markdown).toContain('- `registry/` - Registry data.');
    expect(markdown).toContain('## Operational Notes');
    expect(markdown).toContain('## CLI');
    expect(markdown).toContain('- Use `example` for repository automation.');
    expect(markdown).toContain(
      '- Full command reference: [CLI Reference](docs/generated/cli-command-reference.md) - Generated command details.',
    );
    expect(markdown).toContain('### Command Groups');
    expect(markdown).toContain('| Group | Purpose | Example |');
    expect(markdown).toContain(
      '| [Validation Commands](docs/generated/cli-command-reference.md#validation-commands) (1) | Commands for validating repository metadata and generated artifacts. | `example validate` |',
    );
    expect(markdown).toContain('## Custom Section');
    expect(markdown).toContain('## Domains');
    expect(markdown).toContain('`domain:example-domain` - Example Domain: Top-level domain context.');
    expect(markdown).toContain('## Agent Capabilities');
    expect(markdown).toContain('`capability:agent-skill.ship` - Ship skill: Use when releasing the package.');
    expect(markdown).toContain('## Packages');
    expect(markdown).toContain('[@example/core](docs/agents/components/package.example-core.md) - Core package. Root: `packages/core`. Scripts: `build`, `test`.');
    expect(markdown).not.toContain('document:generated.agents-skills-ship-skill');
    expect(markdown).toContain('Documentation entrypoint: [Docs Index](docs/index.md).');
    expect(markdown).toContain('`workflow:ship`');
    expect(markdown).toContain('`pnpm test` - Run tests.');
    expect(markdown).not.toContain('Private Runbook');
    expect(markdown).not.toContain('notion://page/private');
  });
});
