import { execFile } from 'node:child_process';
import { mkdir, mkdtemp, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { promisify } from 'node:util';

import { describe, expect, it } from 'vitest';

const execFileAsync = promisify(execFile);
const CLI_PATH = path.resolve('dist/index.js');

describe('atlas CLI golden output', () => {
  it('prints concise validation Markdown', async () => {
    const root = await makeAtlasFixture();
    const { stdout } = await execFileAsync('node', [
      CLI_PATH,
      'validate',
      root,
    ]);

    expect(stdout.replace(/\r\n/g, '\n')).toBe(`# Atlas validation

Status: passed
Profile: \`public\`

Entities: 2
Relations: 2
Warnings: 0
Errors: 0
`);
  });

  it('prints diagnostic hints when validation fails', async () => {
    const root = await makeAtlasFixture({
      brokenRelation: true,
    });

    await expect(
      execFileAsync('node', [CLI_PATH, 'validate', root]),
    ).rejects.toMatchObject({
      stdout: expect.stringContaining(
        'Fix: Create the target entity, fix the target ID, or move cross-repo references into a global registry.',
      ),
    });
  });

  it('prints concise doctor Markdown', async () => {
    const root = await makeAtlasFixture();
    const { stdout } = await execFileAsync('node', [
      CLI_PATH,
      'doctor',
      '--path',
      root,
    ]);

    expect(stdout.replace(/\r\n/g, '\n')).toContain(`# Atlas doctor

Status: passed
`);
    expect(stdout).toContain('Commands:');
    expect(stdout).toContain('doctor');
    expect(stdout).toContain('atlas input');
  });

  it('rejects unknown flags instead of treating them as paths', async () => {
    await expect(
      execFileAsync('node', [CLI_PATH, 'validate', '--badflag']),
    ).rejects.toMatchObject({
      stderr: expect.stringContaining('Unknown option: --badflag'),
    });
  });

  it('rejects duplicate positional and --path roots', async () => {
    const root = await makeAtlasFixture();

    await expect(
      execFileAsync('node', [
        CLI_PATH,
        'resolve-path',
        'packages/example.ts',
        root,
        '--path',
        root,
      ]),
    ).rejects.toMatchObject({
      stderr: expect.stringContaining(
        'Use either one positional path or --path <root>, not both.',
      ),
    });
  });

  it('writes usage notes and evaluates local evidence', async () => {
    const root = await makeAtlasFixture();

    const usageNote = await execFileAsync('node', [
      CLI_PATH,
      'usage-note',
      'Change component:example',
      '--path',
      root,
      '--command',
      'context-pack',
      '--entity',
      'component:example',
      '--file',
      'packages/example.ts',
      '--test',
      'pnpm test',
      '--missing-card',
      'add component details',
    ]);

    expect(usageNote.stdout).toContain('# Atlas usage note');
    expect(usageNote.stdout).toContain('Status: written');

    const evaluation = await execFileAsync('node', [
      CLI_PATH,
      'evaluate',
      '--path',
      root,
    ]);

    expect(evaluation.stdout).toContain('# Atlas usage evidence');
    expect(evaluation.stdout).toContain('Receipt count: 1');
    expect(evaluation.stdout).toContain('Missing-card mentions: 1');
  });

  it('checks atlas boundary leaks', async () => {
    const root = await makeAtlasFixture();
    const { stdout } = await execFileAsync('node', [
      CLI_PATH,
      'boundary-check',
      '--path',
      root,
    ]);

    expect(stdout).toContain('# Atlas boundary check');
    expect(stdout).toContain('Status: passed');
  });

  it('suggests cards, checks generated docs, and reports atlas maintenance', async () => {
    const root = await makeAtlasFixture();
    const sourceDir = path.join(root, 'packages', 'example', 'src');
    await mkdir(sourceDir, { recursive: true });
    await writeFile(path.join(sourceDir, 'index.ts'), 'export {};\n');

    const suggestion = await execFileAsync('node', [
      CLI_PATH,
      'suggest-card',
      '--path',
      'packages/example/src/index.ts',
      '--root',
      root,
    ]);

    expect(suggestion.stdout).toContain('# Atlas suggested card');
    expect(suggestion.stdout).toContain('kind: component');

    await execFileAsync('node', [
      CLI_PATH,
      'generate',
      'markdown',
      '--path',
      root,
    ]);
    const check = await execFileAsync('node', [
      CLI_PATH,
      'generate',
      'markdown',
      '--path',
      root,
      '--check',
    ]);

    expect(check.stdout).toContain('# Atlas Markdown check');
    expect(check.stdout).toContain('Status: passed');

    const diff = await execFileAsync('node', [CLI_PATH, 'diff', '--path', root]);
    expect(diff.stdout).toContain('# Atlas diff');
    expect(diff.stdout).toContain('Status: passed');

    await writeFile(
      path.join(root, 'docs', 'agents', 'components', 'old.md'),
      '<!-- Generated by Agent Atlas. Do not edit directly. -->\n\n# Old\n',
    );

    await expect(
      execFileAsync('node', [
        CLI_PATH,
        'generate',
        'markdown',
        '--path',
        root,
        '--check',
      ]),
    ).rejects.toMatchObject({
      stdout: expect.stringContaining('Extra files: 1'),
    });
  });

  it('prints global manifests and generates registry markdown', async () => {
    const registryRoot = path.resolve(
      '..',
      '..',
      'examples',
      'company-cross-repo-sanitized',
    );
    const outputPath = path.join(await mkdtemp(path.join(os.tmpdir(), 'agent-atlas-global-docs-')), 'docs');

    const manifest = await execFileAsync('node', [
      CLI_PATH,
      'global',
      'manifest',
      '--path',
      registryRoot,
    ]);
    expect(manifest.stdout).toContain('# Atlas global manifest');
    expect(manifest.stdout).toContain('Registry version: 1');
    expect(manifest.stdout).toContain('onboarding-api');

    const generated = await execFileAsync('node', [
      CLI_PATH,
      'global',
      'generate',
      'markdown',
      '--path',
      registryRoot,
      '--output',
      outputPath,
    ]);
    expect(generated.stdout).toContain('# Atlas Markdown generation');
    expect(generated.stdout).toContain('Status: generated');

    const check = await execFileAsync('node', [
      CLI_PATH,
      'global',
      'generate',
      'markdown',
      '--path',
      registryRoot,
      '--output',
      outputPath,
      '--check',
    ]);
    expect(check.stdout).toContain('# Atlas Markdown check');
    expect(check.stdout).toContain('Status: passed');
  });
});

async function makeAtlasFixture(
  options: { brokenRelation?: boolean } = {},
): Promise<string> {
  const root = await mkdtemp(path.join(os.tmpdir(), 'agent-atlas-cli-'));
  const componentDir = path.join(root, '.agent-atlas', 'public', 'components');
  const workflowDir = path.join(root, '.agent-atlas', 'public', 'workflows');
  await mkdir(componentDir, { recursive: true });
  await mkdir(workflowDir, { recursive: true });

  await writeFile(
    path.join(componentDir, 'example.yaml'),
    `id: component:example
kind: component
title: Example
summary: Example component.
relations:
  - type: part-of
    target: ${options.brokenRelation ? 'workflow:missing' : 'workflow:example'}
`,
  );

  if (!options.brokenRelation) {
    await writeFile(
      path.join(workflowDir, 'example.yaml'),
      `id: workflow:example
kind: workflow
title: Example Workflow
summary: Example workflow.
relations:
  - type: contains
    target: component:example
`,
    );
  }

  return root;
}
